################################################################################
# Automatically-generated file. Do not edit!
################################################################################

SHELL = cmd.exe

# Each subdirectory must supply rules for building sources it contributes
DSP28xx_SciUtil.obj: E:/GiaotrinhDH/DATN/exampleSixStep/mcb_bldc_sixstep_f28069mLaunchPad_openLoop_ert_rtw/DSP28xx_SciUtil.c $(GEN_OPTS) | $(GEN_FILES) $(GEN_MISC_FILES)
	@echo 'Building file: "$<"'
	@echo 'Invoking: C2000 Compiler'
	"D:/TiC2000_Install/CCS/ccs/tools/compiler/ti-cgt-c2000_22.6.0.LTS/bin/cl2000" --include_path="D:/TiC2000_Install/CCS/ccs/tools/compiler/ti-cgt-c2000_22.6.0.LTS/include" --include_path="E:/GiaotrinhDH/DATN/exampleSixStep" --include_path="C:/Program Files/MATLAB/R2023b/toolbox/c2b/tic2000/inc" --include_path="E:/GiaotrinhDH/DATN/exampleSixStep/mcb_bldc_sixstep_f28069mLaunchPad_openLoop_ert_rtw" --include_path="C:/Program Files/MATLAB/R2023b/extern/include" --include_path="C:/Program Files/MATLAB/R2023b/simulink/include" --include_path="C:/Program Files/MATLAB/R2023b/rtw/c/src" --include_path="C:/Program Files/MATLAB/R2023b/rtw/c/src/ext_mode/common" --include_path="C:/Program Files/MATLAB/R2023b/rtw/c/ert" --include_path="C:/Program Files/MATLAB/R2023b/toolbox/c2b/tic2000/src" --include_path="C:/Program Files/MATLAB/R2023b/toolbox/c2b/tic2000_shared/src" --include_path="C:/Program Files/MATLAB/R2023b/toolbox/c2b/tic2000_shared/inc" --include_path="D:/TiC2000_Install/ControlSUITE/controlSUITE/device_support/f2806x/v151/F2806x_common/include" --include_path="D:/TiC2000_Install/ControlSUITE/controlSUITE/device_support/f2806x/v151/F2806x_headers/include" --include_path="D:/TiC2000_Install/ControlSUITE/controlSUITE/libs/math/CLAmath/v400/include" --include_path="D:/TiC2000_Install/ControlSUITE/controlSUITE/libs/math/IQmath/v160/include" --include_path="C:/Program Files/MATLAB/R2023b/toolbox/shared/can/src/scanutil" --include_path="D:/TiC2000_Install/ControlSUITE/controlSUITE/libs/utilities/hrcap_hccal/type0/v110/include" --include_path="C:/Program Files/MATLAB/R2023b/toolbox/c2b/tic2000_soc/src/ipclite" --include_path="C:/Program Files/MATLAB/R2023b/toolbox/c2b/tic2000_soc/inc/ipclite" --define=MW_SCHEDULER_PRIORITY=1 --define=MODEL=mcb_bldc_sixstep_f28069mLaunchPad_openLoop --define=NUMST=1 --define=NCSTATES=0 --define=HAVESTDIO --define=MODEL_HAS_DYNAMICALLY_LOADED_SFCNS=0 --define=CLASSIC_INTERFACE=0 --define=ALLOCATIONFCN=0 --define=TID01EQ=0 --define=TERMFCN=1 --define=ONESTEPFCN=1 --define=MAT_FILE=0 --define=MULTI_INSTANCE_CODE=0 --define=INTEGER_CODE=0 --define=MT=0 --define=XCP_CUSTOM_PLATFORM --define=EXTMODE_DISABLE_ARGS_PROCESSING=1 --define=MW_PIL_SCIFIFOLEN=4 --define=MW_F2806X --define=STACK_SIZE=1024 --define=__MW_TARGET_USE_HARDWARE_RESOURCES_H__ --define=RT --define=F28069M --define=CPU1 --define=BOOT_FROM_FLASH=1 --define=MW_FAST_RTS_INCLUDED=0 --define=MW_HCCAL_INCLUDED=0 --abi=coffabi -s -v28 -ml --abi=coffabi  --preproc_dependency=$(@:%.obj=%.dep) --preproc_with_compile  --large_memory_model -I$(F28_HEADERS)/include -I$(TI_INCLUDE) -v28 -ml --float_support=fpu32 -DF28069M -DCPU1 -DBOOT_FROM_FLASH=1 --preproc_with_compile --preproc_dependency="$(basename $(<F)).d_raw" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: "$<"'
	@echo ' '

F2806x_Adc.obj: D:/TiC2000_Install/ControlSUITE/controlSUITE/device_support/f2806x/v151/F2806x_common/source/F2806x_Adc.c $(GEN_OPTS) | $(GEN_FILES) $(GEN_MISC_FILES)
	@echo 'Building file: "$<"'
	@echo 'Invoking: C2000 Compiler'
	"D:/TiC2000_Install/CCS/ccs/tools/compiler/ti-cgt-c2000_22.6.0.LTS/bin/cl2000" --include_path="D:/TiC2000_Install/CCS/ccs/tools/compiler/ti-cgt-c2000_22.6.0.LTS/include" --include_path="E:/GiaotrinhDH/DATN/exampleSixStep" --include_path="C:/Program Files/MATLAB/R2023b/toolbox/c2b/tic2000/inc" --include_path="E:/GiaotrinhDH/DATN/exampleSixStep/mcb_bldc_sixstep_f28069mLaunchPad_openLoop_ert_rtw" --include_path="C:/Program Files/MATLAB/R2023b/extern/include" --include_path="C:/Program Files/MATLAB/R2023b/simulink/include" --include_path="C:/Program Files/MATLAB/R2023b/rtw/c/src" --include_path="C:/Program Files/MATLAB/R2023b/rtw/c/src/ext_mode/common" --include_path="C:/Program Files/MATLAB/R2023b/rtw/c/ert" --include_path="C:/Program Files/MATLAB/R2023b/toolbox/c2b/tic2000/src" --include_path="C:/Program Files/MATLAB/R2023b/toolbox/c2b/tic2000_shared/src" --include_path="C:/Program Files/MATLAB/R2023b/toolbox/c2b/tic2000_shared/inc" --include_path="D:/TiC2000_Install/ControlSUITE/controlSUITE/device_support/f2806x/v151/F2806x_common/include" --include_path="D:/TiC2000_Install/ControlSUITE/controlSUITE/device_support/f2806x/v151/F2806x_headers/include" --include_path="D:/TiC2000_Install/ControlSUITE/controlSUITE/libs/math/CLAmath/v400/include" --include_path="D:/TiC2000_Install/ControlSUITE/controlSUITE/libs/math/IQmath/v160/include" --include_path="C:/Program Files/MATLAB/R2023b/toolbox/shared/can/src/scanutil" --include_path="D:/TiC2000_Install/ControlSUITE/controlSUITE/libs/utilities/hrcap_hccal/type0/v110/include" --include_path="C:/Program Files/MATLAB/R2023b/toolbox/c2b/tic2000_soc/src/ipclite" --include_path="C:/Program Files/MATLAB/R2023b/toolbox/c2b/tic2000_soc/inc/ipclite" --define=MW_SCHEDULER_PRIORITY=1 --define=MODEL=mcb_bldc_sixstep_f28069mLaunchPad_openLoop --define=NUMST=1 --define=NCSTATES=0 --define=HAVESTDIO --define=MODEL_HAS_DYNAMICALLY_LOADED_SFCNS=0 --define=CLASSIC_INTERFACE=0 --define=ALLOCATIONFCN=0 --define=TID01EQ=0 --define=TERMFCN=1 --define=ONESTEPFCN=1 --define=MAT_FILE=0 --define=MULTI_INSTANCE_CODE=0 --define=INTEGER_CODE=0 --define=MT=0 --define=XCP_CUSTOM_PLATFORM --define=EXTMODE_DISABLE_ARGS_PROCESSING=1 --define=MW_PIL_SCIFIFOLEN=4 --define=MW_F2806X --define=STACK_SIZE=1024 --define=__MW_TARGET_USE_HARDWARE_RESOURCES_H__ --define=RT --define=F28069M --define=CPU1 --define=BOOT_FROM_FLASH=1 --define=MW_FAST_RTS_INCLUDED=0 --define=MW_HCCAL_INCLUDED=0 --abi=coffabi -s -v28 -ml --abi=coffabi  --preproc_dependency=$(@:%.obj=%.dep) --preproc_with_compile  --large_memory_model -I$(F28_HEADERS)/include -I$(TI_INCLUDE) -v28 -ml --float_support=fpu32 -DF28069M -DCPU1 -DBOOT_FROM_FLASH=1 --preproc_with_compile --preproc_dependency="$(basename $(<F)).d_raw" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: "$<"'
	@echo ' '

F2806x_CodeStartBranch.obj: D:/TiC2000_Install/ControlSUITE/controlSUITE/device_support/f2806x/v151/F2806x_common/source/F2806x_CodeStartBranch.asm $(GEN_OPTS) | $(GEN_FILES) $(GEN_MISC_FILES)
	@echo 'Building file: "$<"'
	@echo 'Invoking: C2000 Compiler'
	"D:/TiC2000_Install/CCS/ccs/tools/compiler/ti-cgt-c2000_22.6.0.LTS/bin/cl2000" --include_path="D:/TiC2000_Install/CCS/ccs/tools/compiler/ti-cgt-c2000_22.6.0.LTS/include" --include_path="E:/GiaotrinhDH/DATN/exampleSixStep" --include_path="C:/Program Files/MATLAB/R2023b/toolbox/c2b/tic2000/inc" --include_path="E:/GiaotrinhDH/DATN/exampleSixStep/mcb_bldc_sixstep_f28069mLaunchPad_openLoop_ert_rtw" --include_path="C:/Program Files/MATLAB/R2023b/extern/include" --include_path="C:/Program Files/MATLAB/R2023b/simulink/include" --include_path="C:/Program Files/MATLAB/R2023b/rtw/c/src" --include_path="C:/Program Files/MATLAB/R2023b/rtw/c/src/ext_mode/common" --include_path="C:/Program Files/MATLAB/R2023b/rtw/c/ert" --include_path="C:/Program Files/MATLAB/R2023b/toolbox/c2b/tic2000/src" --include_path="C:/Program Files/MATLAB/R2023b/toolbox/c2b/tic2000_shared/src" --include_path="C:/Program Files/MATLAB/R2023b/toolbox/c2b/tic2000_shared/inc" --include_path="D:/TiC2000_Install/ControlSUITE/controlSUITE/device_support/f2806x/v151/F2806x_common/include" --include_path="D:/TiC2000_Install/ControlSUITE/controlSUITE/device_support/f2806x/v151/F2806x_headers/include" --include_path="D:/TiC2000_Install/ControlSUITE/controlSUITE/libs/math/CLAmath/v400/include" --include_path="D:/TiC2000_Install/ControlSUITE/controlSUITE/libs/math/IQmath/v160/include" --include_path="C:/Program Files/MATLAB/R2023b/toolbox/shared/can/src/scanutil" --include_path="D:/TiC2000_Install/ControlSUITE/controlSUITE/libs/utilities/hrcap_hccal/type0/v110/include" --include_path="C:/Program Files/MATLAB/R2023b/toolbox/c2b/tic2000_soc/src/ipclite" --include_path="C:/Program Files/MATLAB/R2023b/toolbox/c2b/tic2000_soc/inc/ipclite" --define=MW_SCHEDULER_PRIORITY=1 --define=MODEL=mcb_bldc_sixstep_f28069mLaunchPad_openLoop --define=NUMST=1 --define=NCSTATES=0 --define=HAVESTDIO --define=MODEL_HAS_DYNAMICALLY_LOADED_SFCNS=0 --define=CLASSIC_INTERFACE=0 --define=ALLOCATIONFCN=0 --define=TID01EQ=0 --define=TERMFCN=1 --define=ONESTEPFCN=1 --define=MAT_FILE=0 --define=MULTI_INSTANCE_CODE=0 --define=INTEGER_CODE=0 --define=MT=0 --define=XCP_CUSTOM_PLATFORM --define=EXTMODE_DISABLE_ARGS_PROCESSING=1 --define=MW_PIL_SCIFIFOLEN=4 --define=MW_F2806X --define=STACK_SIZE=1024 --define=__MW_TARGET_USE_HARDWARE_RESOURCES_H__ --define=RT --define=F28069M --define=CPU1 --define=BOOT_FROM_FLASH=1 --define=MW_FAST_RTS_INCLUDED=0 --define=MW_HCCAL_INCLUDED=0 --abi=coffabi -s -v28 -ml --abi=coffabi  --preproc_dependency=$(@:%.obj=%.dep) --preproc_with_compile  --large_memory_model -I$(F28_HEADERS)/include -I$(TI_INCLUDE) -v28 -ml --float_support=fpu32 -DF28069M -DCPU1 -DBOOT_FROM_FLASH=1 --preproc_with_compile --preproc_dependency="$(basename $(<F)).d_raw" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: "$<"'
	@echo ' '

F2806x_CpuTimers.obj: D:/TiC2000_Install/ControlSUITE/controlSUITE/device_support/f2806x/v151/F2806x_common/source/F2806x_CpuTimers.c $(GEN_OPTS) | $(GEN_FILES) $(GEN_MISC_FILES)
	@echo 'Building file: "$<"'
	@echo 'Invoking: C2000 Compiler'
	"D:/TiC2000_Install/CCS/ccs/tools/compiler/ti-cgt-c2000_22.6.0.LTS/bin/cl2000" --include_path="D:/TiC2000_Install/CCS/ccs/tools/compiler/ti-cgt-c2000_22.6.0.LTS/include" --include_path="E:/GiaotrinhDH/DATN/exampleSixStep" --include_path="C:/Program Files/MATLAB/R2023b/toolbox/c2b/tic2000/inc" --include_path="E:/GiaotrinhDH/DATN/exampleSixStep/mcb_bldc_sixstep_f28069mLaunchPad_openLoop_ert_rtw" --include_path="C:/Program Files/MATLAB/R2023b/extern/include" --include_path="C:/Program Files/MATLAB/R2023b/simulink/include" --include_path="C:/Program Files/MATLAB/R2023b/rtw/c/src" --include_path="C:/Program Files/MATLAB/R2023b/rtw/c/src/ext_mode/common" --include_path="C:/Program Files/MATLAB/R2023b/rtw/c/ert" --include_path="C:/Program Files/MATLAB/R2023b/toolbox/c2b/tic2000/src" --include_path="C:/Program Files/MATLAB/R2023b/toolbox/c2b/tic2000_shared/src" --include_path="C:/Program Files/MATLAB/R2023b/toolbox/c2b/tic2000_shared/inc" --include_path="D:/TiC2000_Install/ControlSUITE/controlSUITE/device_support/f2806x/v151/F2806x_common/include" --include_path="D:/TiC2000_Install/ControlSUITE/controlSUITE/device_support/f2806x/v151/F2806x_headers/include" --include_path="D:/TiC2000_Install/ControlSUITE/controlSUITE/libs/math/CLAmath/v400/include" --include_path="D:/TiC2000_Install/ControlSUITE/controlSUITE/libs/math/IQmath/v160/include" --include_path="C:/Program Files/MATLAB/R2023b/toolbox/shared/can/src/scanutil" --include_path="D:/TiC2000_Install/ControlSUITE/controlSUITE/libs/utilities/hrcap_hccal/type0/v110/include" --include_path="C:/Program Files/MATLAB/R2023b/toolbox/c2b/tic2000_soc/src/ipclite" --include_path="C:/Program Files/MATLAB/R2023b/toolbox/c2b/tic2000_soc/inc/ipclite" --define=MW_SCHEDULER_PRIORITY=1 --define=MODEL=mcb_bldc_sixstep_f28069mLaunchPad_openLoop --define=NUMST=1 --define=NCSTATES=0 --define=HAVESTDIO --define=MODEL_HAS_DYNAMICALLY_LOADED_SFCNS=0 --define=CLASSIC_INTERFACE=0 --define=ALLOCATIONFCN=0 --define=TID01EQ=0 --define=TERMFCN=1 --define=ONESTEPFCN=1 --define=MAT_FILE=0 --define=MULTI_INSTANCE_CODE=0 --define=INTEGER_CODE=0 --define=MT=0 --define=XCP_CUSTOM_PLATFORM --define=EXTMODE_DISABLE_ARGS_PROCESSING=1 --define=MW_PIL_SCIFIFOLEN=4 --define=MW_F2806X --define=STACK_SIZE=1024 --define=__MW_TARGET_USE_HARDWARE_RESOURCES_H__ --define=RT --define=F28069M --define=CPU1 --define=BOOT_FROM_FLASH=1 --define=MW_FAST_RTS_INCLUDED=0 --define=MW_HCCAL_INCLUDED=0 --abi=coffabi -s -v28 -ml --abi=coffabi  --preproc_dependency=$(@:%.obj=%.dep) --preproc_with_compile  --large_memory_model -I$(F28_HEADERS)/include -I$(TI_INCLUDE) -v28 -ml --float_support=fpu32 -DF28069M -DCPU1 -DBOOT_FROM_FLASH=1 --preproc_with_compile --preproc_dependency="$(basename $(<F)).d_raw" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: "$<"'
	@echo ' '

F2806x_DefaultIsr.obj: D:/TiC2000_Install/ControlSUITE/controlSUITE/device_support/f2806x/v151/F2806x_common/source/F2806x_DefaultIsr.c $(GEN_OPTS) | $(GEN_FILES) $(GEN_MISC_FILES)
	@echo 'Building file: "$<"'
	@echo 'Invoking: C2000 Compiler'
	"D:/TiC2000_Install/CCS/ccs/tools/compiler/ti-cgt-c2000_22.6.0.LTS/bin/cl2000" --include_path="D:/TiC2000_Install/CCS/ccs/tools/compiler/ti-cgt-c2000_22.6.0.LTS/include" --include_path="E:/GiaotrinhDH/DATN/exampleSixStep" --include_path="C:/Program Files/MATLAB/R2023b/toolbox/c2b/tic2000/inc" --include_path="E:/GiaotrinhDH/DATN/exampleSixStep/mcb_bldc_sixstep_f28069mLaunchPad_openLoop_ert_rtw" --include_path="C:/Program Files/MATLAB/R2023b/extern/include" --include_path="C:/Program Files/MATLAB/R2023b/simulink/include" --include_path="C:/Program Files/MATLAB/R2023b/rtw/c/src" --include_path="C:/Program Files/MATLAB/R2023b/rtw/c/src/ext_mode/common" --include_path="C:/Program Files/MATLAB/R2023b/rtw/c/ert" --include_path="C:/Program Files/MATLAB/R2023b/toolbox/c2b/tic2000/src" --include_path="C:/Program Files/MATLAB/R2023b/toolbox/c2b/tic2000_shared/src" --include_path="C:/Program Files/MATLAB/R2023b/toolbox/c2b/tic2000_shared/inc" --include_path="D:/TiC2000_Install/ControlSUITE/controlSUITE/device_support/f2806x/v151/F2806x_common/include" --include_path="D:/TiC2000_Install/ControlSUITE/controlSUITE/device_support/f2806x/v151/F2806x_headers/include" --include_path="D:/TiC2000_Install/ControlSUITE/controlSUITE/libs/math/CLAmath/v400/include" --include_path="D:/TiC2000_Install/ControlSUITE/controlSUITE/libs/math/IQmath/v160/include" --include_path="C:/Program Files/MATLAB/R2023b/toolbox/shared/can/src/scanutil" --include_path="D:/TiC2000_Install/ControlSUITE/controlSUITE/libs/utilities/hrcap_hccal/type0/v110/include" --include_path="C:/Program Files/MATLAB/R2023b/toolbox/c2b/tic2000_soc/src/ipclite" --include_path="C:/Program Files/MATLAB/R2023b/toolbox/c2b/tic2000_soc/inc/ipclite" --define=MW_SCHEDULER_PRIORITY=1 --define=MODEL=mcb_bldc_sixstep_f28069mLaunchPad_openLoop --define=NUMST=1 --define=NCSTATES=0 --define=HAVESTDIO --define=MODEL_HAS_DYNAMICALLY_LOADED_SFCNS=0 --define=CLASSIC_INTERFACE=0 --define=ALLOCATIONFCN=0 --define=TID01EQ=0 --define=TERMFCN=1 --define=ONESTEPFCN=1 --define=MAT_FILE=0 --define=MULTI_INSTANCE_CODE=0 --define=INTEGER_CODE=0 --define=MT=0 --define=XCP_CUSTOM_PLATFORM --define=EXTMODE_DISABLE_ARGS_PROCESSING=1 --define=MW_PIL_SCIFIFOLEN=4 --define=MW_F2806X --define=STACK_SIZE=1024 --define=__MW_TARGET_USE_HARDWARE_RESOURCES_H__ --define=RT --define=F28069M --define=CPU1 --define=BOOT_FROM_FLASH=1 --define=MW_FAST_RTS_INCLUDED=0 --define=MW_HCCAL_INCLUDED=0 --abi=coffabi -s -v28 -ml --abi=coffabi  --preproc_dependency=$(@:%.obj=%.dep) --preproc_with_compile  --large_memory_model -I$(F28_HEADERS)/include -I$(TI_INCLUDE) -v28 -ml --float_support=fpu32 -DF28069M -DCPU1 -DBOOT_FROM_FLASH=1 --preproc_with_compile --preproc_dependency="$(basename $(<F)).d_raw" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: "$<"'
	@echo ' '

F2806x_Dma.obj: D:/TiC2000_Install/ControlSUITE/controlSUITE/device_support/f2806x/v151/F2806x_common/source/F2806x_Dma.c $(GEN_OPTS) | $(GEN_FILES) $(GEN_MISC_FILES)
	@echo 'Building file: "$<"'
	@echo 'Invoking: C2000 Compiler'
	"D:/TiC2000_Install/CCS/ccs/tools/compiler/ti-cgt-c2000_22.6.0.LTS/bin/cl2000" --include_path="D:/TiC2000_Install/CCS/ccs/tools/compiler/ti-cgt-c2000_22.6.0.LTS/include" --include_path="E:/GiaotrinhDH/DATN/exampleSixStep" --include_path="C:/Program Files/MATLAB/R2023b/toolbox/c2b/tic2000/inc" --include_path="E:/GiaotrinhDH/DATN/exampleSixStep/mcb_bldc_sixstep_f28069mLaunchPad_openLoop_ert_rtw" --include_path="C:/Program Files/MATLAB/R2023b/extern/include" --include_path="C:/Program Files/MATLAB/R2023b/simulink/include" --include_path="C:/Program Files/MATLAB/R2023b/rtw/c/src" --include_path="C:/Program Files/MATLAB/R2023b/rtw/c/src/ext_mode/common" --include_path="C:/Program Files/MATLAB/R2023b/rtw/c/ert" --include_path="C:/Program Files/MATLAB/R2023b/toolbox/c2b/tic2000/src" --include_path="C:/Program Files/MATLAB/R2023b/toolbox/c2b/tic2000_shared/src" --include_path="C:/Program Files/MATLAB/R2023b/toolbox/c2b/tic2000_shared/inc" --include_path="D:/TiC2000_Install/ControlSUITE/controlSUITE/device_support/f2806x/v151/F2806x_common/include" --include_path="D:/TiC2000_Install/ControlSUITE/controlSUITE/device_support/f2806x/v151/F2806x_headers/include" --include_path="D:/TiC2000_Install/ControlSUITE/controlSUITE/libs/math/CLAmath/v400/include" --include_path="D:/TiC2000_Install/ControlSUITE/controlSUITE/libs/math/IQmath/v160/include" --include_path="C:/Program Files/MATLAB/R2023b/toolbox/shared/can/src/scanutil" --include_path="D:/TiC2000_Install/ControlSUITE/controlSUITE/libs/utilities/hrcap_hccal/type0/v110/include" --include_path="C:/Program Files/MATLAB/R2023b/toolbox/c2b/tic2000_soc/src/ipclite" --include_path="C:/Program Files/MATLAB/R2023b/toolbox/c2b/tic2000_soc/inc/ipclite" --define=MW_SCHEDULER_PRIORITY=1 --define=MODEL=mcb_bldc_sixstep_f28069mLaunchPad_openLoop --define=NUMST=1 --define=NCSTATES=0 --define=HAVESTDIO --define=MODEL_HAS_DYNAMICALLY_LOADED_SFCNS=0 --define=CLASSIC_INTERFACE=0 --define=ALLOCATIONFCN=0 --define=TID01EQ=0 --define=TERMFCN=1 --define=ONESTEPFCN=1 --define=MAT_FILE=0 --define=MULTI_INSTANCE_CODE=0 --define=INTEGER_CODE=0 --define=MT=0 --define=XCP_CUSTOM_PLATFORM --define=EXTMODE_DISABLE_ARGS_PROCESSING=1 --define=MW_PIL_SCIFIFOLEN=4 --define=MW_F2806X --define=STACK_SIZE=1024 --define=__MW_TARGET_USE_HARDWARE_RESOURCES_H__ --define=RT --define=F28069M --define=CPU1 --define=BOOT_FROM_FLASH=1 --define=MW_FAST_RTS_INCLUDED=0 --define=MW_HCCAL_INCLUDED=0 --abi=coffabi -s -v28 -ml --abi=coffabi  --preproc_dependency=$(@:%.obj=%.dep) --preproc_with_compile  --large_memory_model -I$(F28_HEADERS)/include -I$(TI_INCLUDE) -v28 -ml --float_support=fpu32 -DF28069M -DCPU1 -DBOOT_FROM_FLASH=1 --preproc_with_compile --preproc_dependency="$(basename $(<F)).d_raw" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: "$<"'
	@echo ' '

F2806x_GlobalVariableDefs.obj: D:/TiC2000_Install/ControlSUITE/controlSUITE/device_support/f2806x/v151/F2806x_headers/source/F2806x_GlobalVariableDefs.c $(GEN_OPTS) | $(GEN_FILES) $(GEN_MISC_FILES)
	@echo 'Building file: "$<"'
	@echo 'Invoking: C2000 Compiler'
	"D:/TiC2000_Install/CCS/ccs/tools/compiler/ti-cgt-c2000_22.6.0.LTS/bin/cl2000" --include_path="D:/TiC2000_Install/CCS/ccs/tools/compiler/ti-cgt-c2000_22.6.0.LTS/include" --include_path="E:/GiaotrinhDH/DATN/exampleSixStep" --include_path="C:/Program Files/MATLAB/R2023b/toolbox/c2b/tic2000/inc" --include_path="E:/GiaotrinhDH/DATN/exampleSixStep/mcb_bldc_sixstep_f28069mLaunchPad_openLoop_ert_rtw" --include_path="C:/Program Files/MATLAB/R2023b/extern/include" --include_path="C:/Program Files/MATLAB/R2023b/simulink/include" --include_path="C:/Program Files/MATLAB/R2023b/rtw/c/src" --include_path="C:/Program Files/MATLAB/R2023b/rtw/c/src/ext_mode/common" --include_path="C:/Program Files/MATLAB/R2023b/rtw/c/ert" --include_path="C:/Program Files/MATLAB/R2023b/toolbox/c2b/tic2000/src" --include_path="C:/Program Files/MATLAB/R2023b/toolbox/c2b/tic2000_shared/src" --include_path="C:/Program Files/MATLAB/R2023b/toolbox/c2b/tic2000_shared/inc" --include_path="D:/TiC2000_Install/ControlSUITE/controlSUITE/device_support/f2806x/v151/F2806x_common/include" --include_path="D:/TiC2000_Install/ControlSUITE/controlSUITE/device_support/f2806x/v151/F2806x_headers/include" --include_path="D:/TiC2000_Install/ControlSUITE/controlSUITE/libs/math/CLAmath/v400/include" --include_path="D:/TiC2000_Install/ControlSUITE/controlSUITE/libs/math/IQmath/v160/include" --include_path="C:/Program Files/MATLAB/R2023b/toolbox/shared/can/src/scanutil" --include_path="D:/TiC2000_Install/ControlSUITE/controlSUITE/libs/utilities/hrcap_hccal/type0/v110/include" --include_path="C:/Program Files/MATLAB/R2023b/toolbox/c2b/tic2000_soc/src/ipclite" --include_path="C:/Program Files/MATLAB/R2023b/toolbox/c2b/tic2000_soc/inc/ipclite" --define=MW_SCHEDULER_PRIORITY=1 --define=MODEL=mcb_bldc_sixstep_f28069mLaunchPad_openLoop --define=NUMST=1 --define=NCSTATES=0 --define=HAVESTDIO --define=MODEL_HAS_DYNAMICALLY_LOADED_SFCNS=0 --define=CLASSIC_INTERFACE=0 --define=ALLOCATIONFCN=0 --define=TID01EQ=0 --define=TERMFCN=1 --define=ONESTEPFCN=1 --define=MAT_FILE=0 --define=MULTI_INSTANCE_CODE=0 --define=INTEGER_CODE=0 --define=MT=0 --define=XCP_CUSTOM_PLATFORM --define=EXTMODE_DISABLE_ARGS_PROCESSING=1 --define=MW_PIL_SCIFIFOLEN=4 --define=MW_F2806X --define=STACK_SIZE=1024 --define=__MW_TARGET_USE_HARDWARE_RESOURCES_H__ --define=RT --define=F28069M --define=CPU1 --define=BOOT_FROM_FLASH=1 --define=MW_FAST_RTS_INCLUDED=0 --define=MW_HCCAL_INCLUDED=0 --abi=coffabi -s -v28 -ml --abi=coffabi  --preproc_dependency=$(@:%.obj=%.dep) --preproc_with_compile  --large_memory_model -I$(F28_HEADERS)/include -I$(TI_INCLUDE) -v28 -ml --float_support=fpu32 -DF28069M -DCPU1 -DBOOT_FROM_FLASH=1 --preproc_with_compile --preproc_dependency="$(basename $(<F)).d_raw" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: "$<"'
	@echo ' '

F2806x_HRCap.obj: D:/TiC2000_Install/ControlSUITE/controlSUITE/device_support/f2806x/v151/F2806x_common/source/F2806x_HRCap.c $(GEN_OPTS) | $(GEN_FILES) $(GEN_MISC_FILES)
	@echo 'Building file: "$<"'
	@echo 'Invoking: C2000 Compiler'
	"D:/TiC2000_Install/CCS/ccs/tools/compiler/ti-cgt-c2000_22.6.0.LTS/bin/cl2000" --include_path="D:/TiC2000_Install/CCS/ccs/tools/compiler/ti-cgt-c2000_22.6.0.LTS/include" --include_path="E:/GiaotrinhDH/DATN/exampleSixStep" --include_path="C:/Program Files/MATLAB/R2023b/toolbox/c2b/tic2000/inc" --include_path="E:/GiaotrinhDH/DATN/exampleSixStep/mcb_bldc_sixstep_f28069mLaunchPad_openLoop_ert_rtw" --include_path="C:/Program Files/MATLAB/R2023b/extern/include" --include_path="C:/Program Files/MATLAB/R2023b/simulink/include" --include_path="C:/Program Files/MATLAB/R2023b/rtw/c/src" --include_path="C:/Program Files/MATLAB/R2023b/rtw/c/src/ext_mode/common" --include_path="C:/Program Files/MATLAB/R2023b/rtw/c/ert" --include_path="C:/Program Files/MATLAB/R2023b/toolbox/c2b/tic2000/src" --include_path="C:/Program Files/MATLAB/R2023b/toolbox/c2b/tic2000_shared/src" --include_path="C:/Program Files/MATLAB/R2023b/toolbox/c2b/tic2000_shared/inc" --include_path="D:/TiC2000_Install/ControlSUITE/controlSUITE/device_support/f2806x/v151/F2806x_common/include" --include_path="D:/TiC2000_Install/ControlSUITE/controlSUITE/device_support/f2806x/v151/F2806x_headers/include" --include_path="D:/TiC2000_Install/ControlSUITE/controlSUITE/libs/math/CLAmath/v400/include" --include_path="D:/TiC2000_Install/ControlSUITE/controlSUITE/libs/math/IQmath/v160/include" --include_path="C:/Program Files/MATLAB/R2023b/toolbox/shared/can/src/scanutil" --include_path="D:/TiC2000_Install/ControlSUITE/controlSUITE/libs/utilities/hrcap_hccal/type0/v110/include" --include_path="C:/Program Files/MATLAB/R2023b/toolbox/c2b/tic2000_soc/src/ipclite" --include_path="C:/Program Files/MATLAB/R2023b/toolbox/c2b/tic2000_soc/inc/ipclite" --define=MW_SCHEDULER_PRIORITY=1 --define=MODEL=mcb_bldc_sixstep_f28069mLaunchPad_openLoop --define=NUMST=1 --define=NCSTATES=0 --define=HAVESTDIO --define=MODEL_HAS_DYNAMICALLY_LOADED_SFCNS=0 --define=CLASSIC_INTERFACE=0 --define=ALLOCATIONFCN=0 --define=TID01EQ=0 --define=TERMFCN=1 --define=ONESTEPFCN=1 --define=MAT_FILE=0 --define=MULTI_INSTANCE_CODE=0 --define=INTEGER_CODE=0 --define=MT=0 --define=XCP_CUSTOM_PLATFORM --define=EXTMODE_DISABLE_ARGS_PROCESSING=1 --define=MW_PIL_SCIFIFOLEN=4 --define=MW_F2806X --define=STACK_SIZE=1024 --define=__MW_TARGET_USE_HARDWARE_RESOURCES_H__ --define=RT --define=F28069M --define=CPU1 --define=BOOT_FROM_FLASH=1 --define=MW_FAST_RTS_INCLUDED=0 --define=MW_HCCAL_INCLUDED=0 --abi=coffabi -s -v28 -ml --abi=coffabi  --preproc_dependency=$(@:%.obj=%.dep) --preproc_with_compile  --large_memory_model -I$(F28_HEADERS)/include -I$(TI_INCLUDE) -v28 -ml --float_support=fpu32 -DF28069M -DCPU1 -DBOOT_FROM_FLASH=1 --preproc_with_compile --preproc_dependency="$(basename $(<F)).d_raw" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: "$<"'
	@echo ' '

F2806x_PieCtrl.obj: D:/TiC2000_Install/ControlSUITE/controlSUITE/device_support/f2806x/v151/F2806x_common/source/F2806x_PieCtrl.c $(GEN_OPTS) | $(GEN_FILES) $(GEN_MISC_FILES)
	@echo 'Building file: "$<"'
	@echo 'Invoking: C2000 Compiler'
	"D:/TiC2000_Install/CCS/ccs/tools/compiler/ti-cgt-c2000_22.6.0.LTS/bin/cl2000" --include_path="D:/TiC2000_Install/CCS/ccs/tools/compiler/ti-cgt-c2000_22.6.0.LTS/include" --include_path="E:/GiaotrinhDH/DATN/exampleSixStep" --include_path="C:/Program Files/MATLAB/R2023b/toolbox/c2b/tic2000/inc" --include_path="E:/GiaotrinhDH/DATN/exampleSixStep/mcb_bldc_sixstep_f28069mLaunchPad_openLoop_ert_rtw" --include_path="C:/Program Files/MATLAB/R2023b/extern/include" --include_path="C:/Program Files/MATLAB/R2023b/simulink/include" --include_path="C:/Program Files/MATLAB/R2023b/rtw/c/src" --include_path="C:/Program Files/MATLAB/R2023b/rtw/c/src/ext_mode/common" --include_path="C:/Program Files/MATLAB/R2023b/rtw/c/ert" --include_path="C:/Program Files/MATLAB/R2023b/toolbox/c2b/tic2000/src" --include_path="C:/Program Files/MATLAB/R2023b/toolbox/c2b/tic2000_shared/src" --include_path="C:/Program Files/MATLAB/R2023b/toolbox/c2b/tic2000_shared/inc" --include_path="D:/TiC2000_Install/ControlSUITE/controlSUITE/device_support/f2806x/v151/F2806x_common/include" --include_path="D:/TiC2000_Install/ControlSUITE/controlSUITE/device_support/f2806x/v151/F2806x_headers/include" --include_path="D:/TiC2000_Install/ControlSUITE/controlSUITE/libs/math/CLAmath/v400/include" --include_path="D:/TiC2000_Install/ControlSUITE/controlSUITE/libs/math/IQmath/v160/include" --include_path="C:/Program Files/MATLAB/R2023b/toolbox/shared/can/src/scanutil" --include_path="D:/TiC2000_Install/ControlSUITE/controlSUITE/libs/utilities/hrcap_hccal/type0/v110/include" --include_path="C:/Program Files/MATLAB/R2023b/toolbox/c2b/tic2000_soc/src/ipclite" --include_path="C:/Program Files/MATLAB/R2023b/toolbox/c2b/tic2000_soc/inc/ipclite" --define=MW_SCHEDULER_PRIORITY=1 --define=MODEL=mcb_bldc_sixstep_f28069mLaunchPad_openLoop --define=NUMST=1 --define=NCSTATES=0 --define=HAVESTDIO --define=MODEL_HAS_DYNAMICALLY_LOADED_SFCNS=0 --define=CLASSIC_INTERFACE=0 --define=ALLOCATIONFCN=0 --define=TID01EQ=0 --define=TERMFCN=1 --define=ONESTEPFCN=1 --define=MAT_FILE=0 --define=MULTI_INSTANCE_CODE=0 --define=INTEGER_CODE=0 --define=MT=0 --define=XCP_CUSTOM_PLATFORM --define=EXTMODE_DISABLE_ARGS_PROCESSING=1 --define=MW_PIL_SCIFIFOLEN=4 --define=MW_F2806X --define=STACK_SIZE=1024 --define=__MW_TARGET_USE_HARDWARE_RESOURCES_H__ --define=RT --define=F28069M --define=CPU1 --define=BOOT_FROM_FLASH=1 --define=MW_FAST_RTS_INCLUDED=0 --define=MW_HCCAL_INCLUDED=0 --abi=coffabi -s -v28 -ml --abi=coffabi  --preproc_dependency=$(@:%.obj=%.dep) --preproc_with_compile  --large_memory_model -I$(F28_HEADERS)/include -I$(TI_INCLUDE) -v28 -ml --float_support=fpu32 -DF28069M -DCPU1 -DBOOT_FROM_FLASH=1 --preproc_with_compile --preproc_dependency="$(basename $(<F)).d_raw" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: "$<"'
	@echo ' '

F2806x_PieVect.obj: D:/TiC2000_Install/ControlSUITE/controlSUITE/device_support/f2806x/v151/F2806x_common/source/F2806x_PieVect.c $(GEN_OPTS) | $(GEN_FILES) $(GEN_MISC_FILES)
	@echo 'Building file: "$<"'
	@echo 'Invoking: C2000 Compiler'
	"D:/TiC2000_Install/CCS/ccs/tools/compiler/ti-cgt-c2000_22.6.0.LTS/bin/cl2000" --include_path="D:/TiC2000_Install/CCS/ccs/tools/compiler/ti-cgt-c2000_22.6.0.LTS/include" --include_path="E:/GiaotrinhDH/DATN/exampleSixStep" --include_path="C:/Program Files/MATLAB/R2023b/toolbox/c2b/tic2000/inc" --include_path="E:/GiaotrinhDH/DATN/exampleSixStep/mcb_bldc_sixstep_f28069mLaunchPad_openLoop_ert_rtw" --include_path="C:/Program Files/MATLAB/R2023b/extern/include" --include_path="C:/Program Files/MATLAB/R2023b/simulink/include" --include_path="C:/Program Files/MATLAB/R2023b/rtw/c/src" --include_path="C:/Program Files/MATLAB/R2023b/rtw/c/src/ext_mode/common" --include_path="C:/Program Files/MATLAB/R2023b/rtw/c/ert" --include_path="C:/Program Files/MATLAB/R2023b/toolbox/c2b/tic2000/src" --include_path="C:/Program Files/MATLAB/R2023b/toolbox/c2b/tic2000_shared/src" --include_path="C:/Program Files/MATLAB/R2023b/toolbox/c2b/tic2000_shared/inc" --include_path="D:/TiC2000_Install/ControlSUITE/controlSUITE/device_support/f2806x/v151/F2806x_common/include" --include_path="D:/TiC2000_Install/ControlSUITE/controlSUITE/device_support/f2806x/v151/F2806x_headers/include" --include_path="D:/TiC2000_Install/ControlSUITE/controlSUITE/libs/math/CLAmath/v400/include" --include_path="D:/TiC2000_Install/ControlSUITE/controlSUITE/libs/math/IQmath/v160/include" --include_path="C:/Program Files/MATLAB/R2023b/toolbox/shared/can/src/scanutil" --include_path="D:/TiC2000_Install/ControlSUITE/controlSUITE/libs/utilities/hrcap_hccal/type0/v110/include" --include_path="C:/Program Files/MATLAB/R2023b/toolbox/c2b/tic2000_soc/src/ipclite" --include_path="C:/Program Files/MATLAB/R2023b/toolbox/c2b/tic2000_soc/inc/ipclite" --define=MW_SCHEDULER_PRIORITY=1 --define=MODEL=mcb_bldc_sixstep_f28069mLaunchPad_openLoop --define=NUMST=1 --define=NCSTATES=0 --define=HAVESTDIO --define=MODEL_HAS_DYNAMICALLY_LOADED_SFCNS=0 --define=CLASSIC_INTERFACE=0 --define=ALLOCATIONFCN=0 --define=TID01EQ=0 --define=TERMFCN=1 --define=ONESTEPFCN=1 --define=MAT_FILE=0 --define=MULTI_INSTANCE_CODE=0 --define=INTEGER_CODE=0 --define=MT=0 --define=XCP_CUSTOM_PLATFORM --define=EXTMODE_DISABLE_ARGS_PROCESSING=1 --define=MW_PIL_SCIFIFOLEN=4 --define=MW_F2806X --define=STACK_SIZE=1024 --define=__MW_TARGET_USE_HARDWARE_RESOURCES_H__ --define=RT --define=F28069M --define=CPU1 --define=BOOT_FROM_FLASH=1 --define=MW_FAST_RTS_INCLUDED=0 --define=MW_HCCAL_INCLUDED=0 --abi=coffabi -s -v28 -ml --abi=coffabi  --preproc_dependency=$(@:%.obj=%.dep) --preproc_with_compile  --large_memory_model -I$(F28_HEADERS)/include -I$(TI_INCLUDE) -v28 -ml --float_support=fpu32 -DF28069M -DCPU1 -DBOOT_FROM_FLASH=1 --preproc_with_compile --preproc_dependency="$(basename $(<F)).d_raw" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: "$<"'
	@echo ' '

F2806x_SysCtrl.obj: D:/TiC2000_Install/ControlSUITE/controlSUITE/device_support/f2806x/v151/F2806x_common/source/F2806x_SysCtrl.c $(GEN_OPTS) | $(GEN_FILES) $(GEN_MISC_FILES)
	@echo 'Building file: "$<"'
	@echo 'Invoking: C2000 Compiler'
	"D:/TiC2000_Install/CCS/ccs/tools/compiler/ti-cgt-c2000_22.6.0.LTS/bin/cl2000" --include_path="D:/TiC2000_Install/CCS/ccs/tools/compiler/ti-cgt-c2000_22.6.0.LTS/include" --include_path="E:/GiaotrinhDH/DATN/exampleSixStep" --include_path="C:/Program Files/MATLAB/R2023b/toolbox/c2b/tic2000/inc" --include_path="E:/GiaotrinhDH/DATN/exampleSixStep/mcb_bldc_sixstep_f28069mLaunchPad_openLoop_ert_rtw" --include_path="C:/Program Files/MATLAB/R2023b/extern/include" --include_path="C:/Program Files/MATLAB/R2023b/simulink/include" --include_path="C:/Program Files/MATLAB/R2023b/rtw/c/src" --include_path="C:/Program Files/MATLAB/R2023b/rtw/c/src/ext_mode/common" --include_path="C:/Program Files/MATLAB/R2023b/rtw/c/ert" --include_path="C:/Program Files/MATLAB/R2023b/toolbox/c2b/tic2000/src" --include_path="C:/Program Files/MATLAB/R2023b/toolbox/c2b/tic2000_shared/src" --include_path="C:/Program Files/MATLAB/R2023b/toolbox/c2b/tic2000_shared/inc" --include_path="D:/TiC2000_Install/ControlSUITE/controlSUITE/device_support/f2806x/v151/F2806x_common/include" --include_path="D:/TiC2000_Install/ControlSUITE/controlSUITE/device_support/f2806x/v151/F2806x_headers/include" --include_path="D:/TiC2000_Install/ControlSUITE/controlSUITE/libs/math/CLAmath/v400/include" --include_path="D:/TiC2000_Install/ControlSUITE/controlSUITE/libs/math/IQmath/v160/include" --include_path="C:/Program Files/MATLAB/R2023b/toolbox/shared/can/src/scanutil" --include_path="D:/TiC2000_Install/ControlSUITE/controlSUITE/libs/utilities/hrcap_hccal/type0/v110/include" --include_path="C:/Program Files/MATLAB/R2023b/toolbox/c2b/tic2000_soc/src/ipclite" --include_path="C:/Program Files/MATLAB/R2023b/toolbox/c2b/tic2000_soc/inc/ipclite" --define=MW_SCHEDULER_PRIORITY=1 --define=MODEL=mcb_bldc_sixstep_f28069mLaunchPad_openLoop --define=NUMST=1 --define=NCSTATES=0 --define=HAVESTDIO --define=MODEL_HAS_DYNAMICALLY_LOADED_SFCNS=0 --define=CLASSIC_INTERFACE=0 --define=ALLOCATIONFCN=0 --define=TID01EQ=0 --define=TERMFCN=1 --define=ONESTEPFCN=1 --define=MAT_FILE=0 --define=MULTI_INSTANCE_CODE=0 --define=INTEGER_CODE=0 --define=MT=0 --define=XCP_CUSTOM_PLATFORM --define=EXTMODE_DISABLE_ARGS_PROCESSING=1 --define=MW_PIL_SCIFIFOLEN=4 --define=MW_F2806X --define=STACK_SIZE=1024 --define=__MW_TARGET_USE_HARDWARE_RESOURCES_H__ --define=RT --define=F28069M --define=CPU1 --define=BOOT_FROM_FLASH=1 --define=MW_FAST_RTS_INCLUDED=0 --define=MW_HCCAL_INCLUDED=0 --abi=coffabi -s -v28 -ml --abi=coffabi  --preproc_dependency=$(@:%.obj=%.dep) --preproc_with_compile  --large_memory_model -I$(F28_HEADERS)/include -I$(TI_INCLUDE) -v28 -ml --float_support=fpu32 -DF28069M -DCPU1 -DBOOT_FROM_FLASH=1 --preproc_with_compile --preproc_dependency="$(basename $(<F)).d_raw" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: "$<"'
	@echo ' '

F2806x_usDelay.obj: D:/TiC2000_Install/ControlSUITE/controlSUITE/device_support/f2806x/v151/F2806x_common/source/F2806x_usDelay.asm $(GEN_OPTS) | $(GEN_FILES) $(GEN_MISC_FILES)
	@echo 'Building file: "$<"'
	@echo 'Invoking: C2000 Compiler'
	"D:/TiC2000_Install/CCS/ccs/tools/compiler/ti-cgt-c2000_22.6.0.LTS/bin/cl2000" --include_path="D:/TiC2000_Install/CCS/ccs/tools/compiler/ti-cgt-c2000_22.6.0.LTS/include" --include_path="E:/GiaotrinhDH/DATN/exampleSixStep" --include_path="C:/Program Files/MATLAB/R2023b/toolbox/c2b/tic2000/inc" --include_path="E:/GiaotrinhDH/DATN/exampleSixStep/mcb_bldc_sixstep_f28069mLaunchPad_openLoop_ert_rtw" --include_path="C:/Program Files/MATLAB/R2023b/extern/include" --include_path="C:/Program Files/MATLAB/R2023b/simulink/include" --include_path="C:/Program Files/MATLAB/R2023b/rtw/c/src" --include_path="C:/Program Files/MATLAB/R2023b/rtw/c/src/ext_mode/common" --include_path="C:/Program Files/MATLAB/R2023b/rtw/c/ert" --include_path="C:/Program Files/MATLAB/R2023b/toolbox/c2b/tic2000/src" --include_path="C:/Program Files/MATLAB/R2023b/toolbox/c2b/tic2000_shared/src" --include_path="C:/Program Files/MATLAB/R2023b/toolbox/c2b/tic2000_shared/inc" --include_path="D:/TiC2000_Install/ControlSUITE/controlSUITE/device_support/f2806x/v151/F2806x_common/include" --include_path="D:/TiC2000_Install/ControlSUITE/controlSUITE/device_support/f2806x/v151/F2806x_headers/include" --include_path="D:/TiC2000_Install/ControlSUITE/controlSUITE/libs/math/CLAmath/v400/include" --include_path="D:/TiC2000_Install/ControlSUITE/controlSUITE/libs/math/IQmath/v160/include" --include_path="C:/Program Files/MATLAB/R2023b/toolbox/shared/can/src/scanutil" --include_path="D:/TiC2000_Install/ControlSUITE/controlSUITE/libs/utilities/hrcap_hccal/type0/v110/include" --include_path="C:/Program Files/MATLAB/R2023b/toolbox/c2b/tic2000_soc/src/ipclite" --include_path="C:/Program Files/MATLAB/R2023b/toolbox/c2b/tic2000_soc/inc/ipclite" --define=MW_SCHEDULER_PRIORITY=1 --define=MODEL=mcb_bldc_sixstep_f28069mLaunchPad_openLoop --define=NUMST=1 --define=NCSTATES=0 --define=HAVESTDIO --define=MODEL_HAS_DYNAMICALLY_LOADED_SFCNS=0 --define=CLASSIC_INTERFACE=0 --define=ALLOCATIONFCN=0 --define=TID01EQ=0 --define=TERMFCN=1 --define=ONESTEPFCN=1 --define=MAT_FILE=0 --define=MULTI_INSTANCE_CODE=0 --define=INTEGER_CODE=0 --define=MT=0 --define=XCP_CUSTOM_PLATFORM --define=EXTMODE_DISABLE_ARGS_PROCESSING=1 --define=MW_PIL_SCIFIFOLEN=4 --define=MW_F2806X --define=STACK_SIZE=1024 --define=__MW_TARGET_USE_HARDWARE_RESOURCES_H__ --define=RT --define=F28069M --define=CPU1 --define=BOOT_FROM_FLASH=1 --define=MW_FAST_RTS_INCLUDED=0 --define=MW_HCCAL_INCLUDED=0 --abi=coffabi -s -v28 -ml --abi=coffabi  --preproc_dependency=$(@:%.obj=%.dep) --preproc_with_compile  --large_memory_model -I$(F28_HEADERS)/include -I$(TI_INCLUDE) -v28 -ml --float_support=fpu32 -DF28069M -DCPU1 -DBOOT_FROM_FLASH=1 --preproc_with_compile --preproc_dependency="$(basename $(<F)).d_raw" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: "$<"'
	@echo ' '

MW_c2000ISR.obj: C:/Program\ Files/MATLAB/R2023b/toolbox/c2b/tic2000/src/MW_c2000ISR.c $(GEN_OPTS) | $(GEN_FILES) $(GEN_MISC_FILES)
	@echo 'Building file: "$<"'
	@echo 'Invoking: C2000 Compiler'
	"D:/TiC2000_Install/CCS/ccs/tools/compiler/ti-cgt-c2000_22.6.0.LTS/bin/cl2000" --include_path="D:/TiC2000_Install/CCS/ccs/tools/compiler/ti-cgt-c2000_22.6.0.LTS/include" --include_path="E:/GiaotrinhDH/DATN/exampleSixStep" --include_path="C:/Program Files/MATLAB/R2023b/toolbox/c2b/tic2000/inc" --include_path="E:/GiaotrinhDH/DATN/exampleSixStep/mcb_bldc_sixstep_f28069mLaunchPad_openLoop_ert_rtw" --include_path="C:/Program Files/MATLAB/R2023b/extern/include" --include_path="C:/Program Files/MATLAB/R2023b/simulink/include" --include_path="C:/Program Files/MATLAB/R2023b/rtw/c/src" --include_path="C:/Program Files/MATLAB/R2023b/rtw/c/src/ext_mode/common" --include_path="C:/Program Files/MATLAB/R2023b/rtw/c/ert" --include_path="C:/Program Files/MATLAB/R2023b/toolbox/c2b/tic2000/src" --include_path="C:/Program Files/MATLAB/R2023b/toolbox/c2b/tic2000_shared/src" --include_path="C:/Program Files/MATLAB/R2023b/toolbox/c2b/tic2000_shared/inc" --include_path="D:/TiC2000_Install/ControlSUITE/controlSUITE/device_support/f2806x/v151/F2806x_common/include" --include_path="D:/TiC2000_Install/ControlSUITE/controlSUITE/device_support/f2806x/v151/F2806x_headers/include" --include_path="D:/TiC2000_Install/ControlSUITE/controlSUITE/libs/math/CLAmath/v400/include" --include_path="D:/TiC2000_Install/ControlSUITE/controlSUITE/libs/math/IQmath/v160/include" --include_path="C:/Program Files/MATLAB/R2023b/toolbox/shared/can/src/scanutil" --include_path="D:/TiC2000_Install/ControlSUITE/controlSUITE/libs/utilities/hrcap_hccal/type0/v110/include" --include_path="C:/Program Files/MATLAB/R2023b/toolbox/c2b/tic2000_soc/src/ipclite" --include_path="C:/Program Files/MATLAB/R2023b/toolbox/c2b/tic2000_soc/inc/ipclite" --define=MW_SCHEDULER_PRIORITY=1 --define=MODEL=mcb_bldc_sixstep_f28069mLaunchPad_openLoop --define=NUMST=1 --define=NCSTATES=0 --define=HAVESTDIO --define=MODEL_HAS_DYNAMICALLY_LOADED_SFCNS=0 --define=CLASSIC_INTERFACE=0 --define=ALLOCATIONFCN=0 --define=TID01EQ=0 --define=TERMFCN=1 --define=ONESTEPFCN=1 --define=MAT_FILE=0 --define=MULTI_INSTANCE_CODE=0 --define=INTEGER_CODE=0 --define=MT=0 --define=XCP_CUSTOM_PLATFORM --define=EXTMODE_DISABLE_ARGS_PROCESSING=1 --define=MW_PIL_SCIFIFOLEN=4 --define=MW_F2806X --define=STACK_SIZE=1024 --define=__MW_TARGET_USE_HARDWARE_RESOURCES_H__ --define=RT --define=F28069M --define=CPU1 --define=BOOT_FROM_FLASH=1 --define=MW_FAST_RTS_INCLUDED=0 --define=MW_HCCAL_INCLUDED=0 --abi=coffabi -s -v28 -ml --abi=coffabi  --preproc_dependency=$(@:%.obj=%.dep) --preproc_with_compile  --large_memory_model -I$(F28_HEADERS)/include -I$(TI_INCLUDE) -v28 -ml --float_support=fpu32 -DF28069M -DCPU1 -DBOOT_FROM_FLASH=1 --preproc_with_compile --preproc_dependency="$(basename $(<F)).d_raw" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: "$<"'
	@echo ' '

MW_c28xGPIO.obj: C:/Program\ Files/MATLAB/R2023b/toolbox/c2b/tic2000_shared/src/MW_c28xGPIO.c $(GEN_OPTS) | $(GEN_FILES) $(GEN_MISC_FILES)
	@echo 'Building file: "$<"'
	@echo 'Invoking: C2000 Compiler'
	"D:/TiC2000_Install/CCS/ccs/tools/compiler/ti-cgt-c2000_22.6.0.LTS/bin/cl2000" --include_path="D:/TiC2000_Install/CCS/ccs/tools/compiler/ti-cgt-c2000_22.6.0.LTS/include" --include_path="E:/GiaotrinhDH/DATN/exampleSixStep" --include_path="C:/Program Files/MATLAB/R2023b/toolbox/c2b/tic2000/inc" --include_path="E:/GiaotrinhDH/DATN/exampleSixStep/mcb_bldc_sixstep_f28069mLaunchPad_openLoop_ert_rtw" --include_path="C:/Program Files/MATLAB/R2023b/extern/include" --include_path="C:/Program Files/MATLAB/R2023b/simulink/include" --include_path="C:/Program Files/MATLAB/R2023b/rtw/c/src" --include_path="C:/Program Files/MATLAB/R2023b/rtw/c/src/ext_mode/common" --include_path="C:/Program Files/MATLAB/R2023b/rtw/c/ert" --include_path="C:/Program Files/MATLAB/R2023b/toolbox/c2b/tic2000/src" --include_path="C:/Program Files/MATLAB/R2023b/toolbox/c2b/tic2000_shared/src" --include_path="C:/Program Files/MATLAB/R2023b/toolbox/c2b/tic2000_shared/inc" --include_path="D:/TiC2000_Install/ControlSUITE/controlSUITE/device_support/f2806x/v151/F2806x_common/include" --include_path="D:/TiC2000_Install/ControlSUITE/controlSUITE/device_support/f2806x/v151/F2806x_headers/include" --include_path="D:/TiC2000_Install/ControlSUITE/controlSUITE/libs/math/CLAmath/v400/include" --include_path="D:/TiC2000_Install/ControlSUITE/controlSUITE/libs/math/IQmath/v160/include" --include_path="C:/Program Files/MATLAB/R2023b/toolbox/shared/can/src/scanutil" --include_path="D:/TiC2000_Install/ControlSUITE/controlSUITE/libs/utilities/hrcap_hccal/type0/v110/include" --include_path="C:/Program Files/MATLAB/R2023b/toolbox/c2b/tic2000_soc/src/ipclite" --include_path="C:/Program Files/MATLAB/R2023b/toolbox/c2b/tic2000_soc/inc/ipclite" --define=MW_SCHEDULER_PRIORITY=1 --define=MODEL=mcb_bldc_sixstep_f28069mLaunchPad_openLoop --define=NUMST=1 --define=NCSTATES=0 --define=HAVESTDIO --define=MODEL_HAS_DYNAMICALLY_LOADED_SFCNS=0 --define=CLASSIC_INTERFACE=0 --define=ALLOCATIONFCN=0 --define=TID01EQ=0 --define=TERMFCN=1 --define=ONESTEPFCN=1 --define=MAT_FILE=0 --define=MULTI_INSTANCE_CODE=0 --define=INTEGER_CODE=0 --define=MT=0 --define=XCP_CUSTOM_PLATFORM --define=EXTMODE_DISABLE_ARGS_PROCESSING=1 --define=MW_PIL_SCIFIFOLEN=4 --define=MW_F2806X --define=STACK_SIZE=1024 --define=__MW_TARGET_USE_HARDWARE_RESOURCES_H__ --define=RT --define=F28069M --define=CPU1 --define=BOOT_FROM_FLASH=1 --define=MW_FAST_RTS_INCLUDED=0 --define=MW_HCCAL_INCLUDED=0 --abi=coffabi -s -v28 -ml --abi=coffabi  --preproc_dependency=$(@:%.obj=%.dep) --preproc_with_compile  --large_memory_model -I$(F28_HEADERS)/include -I$(TI_INCLUDE) -v28 -ml --float_support=fpu32 -DF28069M -DCPU1 -DBOOT_FROM_FLASH=1 --preproc_with_compile --preproc_dependency="$(basename $(<F)).d_raw" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: "$<"'
	@echo ' '

MW_c28xGlobalInterrupts.obj: C:/Program\ Files/MATLAB/R2023b/toolbox/c2b/tic2000_shared/src/MW_c28xGlobalInterrupts.c $(GEN_OPTS) | $(GEN_FILES) $(GEN_MISC_FILES)
	@echo 'Building file: "$<"'
	@echo 'Invoking: C2000 Compiler'
	"D:/TiC2000_Install/CCS/ccs/tools/compiler/ti-cgt-c2000_22.6.0.LTS/bin/cl2000" --include_path="D:/TiC2000_Install/CCS/ccs/tools/compiler/ti-cgt-c2000_22.6.0.LTS/include" --include_path="E:/GiaotrinhDH/DATN/exampleSixStep" --include_path="C:/Program Files/MATLAB/R2023b/toolbox/c2b/tic2000/inc" --include_path="E:/GiaotrinhDH/DATN/exampleSixStep/mcb_bldc_sixstep_f28069mLaunchPad_openLoop_ert_rtw" --include_path="C:/Program Files/MATLAB/R2023b/extern/include" --include_path="C:/Program Files/MATLAB/R2023b/simulink/include" --include_path="C:/Program Files/MATLAB/R2023b/rtw/c/src" --include_path="C:/Program Files/MATLAB/R2023b/rtw/c/src/ext_mode/common" --include_path="C:/Program Files/MATLAB/R2023b/rtw/c/ert" --include_path="C:/Program Files/MATLAB/R2023b/toolbox/c2b/tic2000/src" --include_path="C:/Program Files/MATLAB/R2023b/toolbox/c2b/tic2000_shared/src" --include_path="C:/Program Files/MATLAB/R2023b/toolbox/c2b/tic2000_shared/inc" --include_path="D:/TiC2000_Install/ControlSUITE/controlSUITE/device_support/f2806x/v151/F2806x_common/include" --include_path="D:/TiC2000_Install/ControlSUITE/controlSUITE/device_support/f2806x/v151/F2806x_headers/include" --include_path="D:/TiC2000_Install/ControlSUITE/controlSUITE/libs/math/CLAmath/v400/include" --include_path="D:/TiC2000_Install/ControlSUITE/controlSUITE/libs/math/IQmath/v160/include" --include_path="C:/Program Files/MATLAB/R2023b/toolbox/shared/can/src/scanutil" --include_path="D:/TiC2000_Install/ControlSUITE/controlSUITE/libs/utilities/hrcap_hccal/type0/v110/include" --include_path="C:/Program Files/MATLAB/R2023b/toolbox/c2b/tic2000_soc/src/ipclite" --include_path="C:/Program Files/MATLAB/R2023b/toolbox/c2b/tic2000_soc/inc/ipclite" --define=MW_SCHEDULER_PRIORITY=1 --define=MODEL=mcb_bldc_sixstep_f28069mLaunchPad_openLoop --define=NUMST=1 --define=NCSTATES=0 --define=HAVESTDIO --define=MODEL_HAS_DYNAMICALLY_LOADED_SFCNS=0 --define=CLASSIC_INTERFACE=0 --define=ALLOCATIONFCN=0 --define=TID01EQ=0 --define=TERMFCN=1 --define=ONESTEPFCN=1 --define=MAT_FILE=0 --define=MULTI_INSTANCE_CODE=0 --define=INTEGER_CODE=0 --define=MT=0 --define=XCP_CUSTOM_PLATFORM --define=EXTMODE_DISABLE_ARGS_PROCESSING=1 --define=MW_PIL_SCIFIFOLEN=4 --define=MW_F2806X --define=STACK_SIZE=1024 --define=__MW_TARGET_USE_HARDWARE_RESOURCES_H__ --define=RT --define=F28069M --define=CPU1 --define=BOOT_FROM_FLASH=1 --define=MW_FAST_RTS_INCLUDED=0 --define=MW_HCCAL_INCLUDED=0 --abi=coffabi -s -v28 -ml --abi=coffabi  --preproc_dependency=$(@:%.obj=%.dep) --preproc_with_compile  --large_memory_model -I$(F28_HEADERS)/include -I$(TI_INCLUDE) -v28 -ml --float_support=fpu32 -DF28069M -DCPU1 -DBOOT_FROM_FLASH=1 --preproc_with_compile --preproc_dependency="$(basename $(<F)).d_raw" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: "$<"'
	@echo ' '

MW_c28xx_adc.obj: E:/GiaotrinhDH/DATN/exampleSixStep/mcb_bldc_sixstep_f28069mLaunchPad_openLoop_ert_rtw/MW_c28xx_adc.c $(GEN_OPTS) | $(GEN_FILES) $(GEN_MISC_FILES)
	@echo 'Building file: "$<"'
	@echo 'Invoking: C2000 Compiler'
	"D:/TiC2000_Install/CCS/ccs/tools/compiler/ti-cgt-c2000_22.6.0.LTS/bin/cl2000" --include_path="D:/TiC2000_Install/CCS/ccs/tools/compiler/ti-cgt-c2000_22.6.0.LTS/include" --include_path="E:/GiaotrinhDH/DATN/exampleSixStep" --include_path="C:/Program Files/MATLAB/R2023b/toolbox/c2b/tic2000/inc" --include_path="E:/GiaotrinhDH/DATN/exampleSixStep/mcb_bldc_sixstep_f28069mLaunchPad_openLoop_ert_rtw" --include_path="C:/Program Files/MATLAB/R2023b/extern/include" --include_path="C:/Program Files/MATLAB/R2023b/simulink/include" --include_path="C:/Program Files/MATLAB/R2023b/rtw/c/src" --include_path="C:/Program Files/MATLAB/R2023b/rtw/c/src/ext_mode/common" --include_path="C:/Program Files/MATLAB/R2023b/rtw/c/ert" --include_path="C:/Program Files/MATLAB/R2023b/toolbox/c2b/tic2000/src" --include_path="C:/Program Files/MATLAB/R2023b/toolbox/c2b/tic2000_shared/src" --include_path="C:/Program Files/MATLAB/R2023b/toolbox/c2b/tic2000_shared/inc" --include_path="D:/TiC2000_Install/ControlSUITE/controlSUITE/device_support/f2806x/v151/F2806x_common/include" --include_path="D:/TiC2000_Install/ControlSUITE/controlSUITE/device_support/f2806x/v151/F2806x_headers/include" --include_path="D:/TiC2000_Install/ControlSUITE/controlSUITE/libs/math/CLAmath/v400/include" --include_path="D:/TiC2000_Install/ControlSUITE/controlSUITE/libs/math/IQmath/v160/include" --include_path="C:/Program Files/MATLAB/R2023b/toolbox/shared/can/src/scanutil" --include_path="D:/TiC2000_Install/ControlSUITE/controlSUITE/libs/utilities/hrcap_hccal/type0/v110/include" --include_path="C:/Program Files/MATLAB/R2023b/toolbox/c2b/tic2000_soc/src/ipclite" --include_path="C:/Program Files/MATLAB/R2023b/toolbox/c2b/tic2000_soc/inc/ipclite" --define=MW_SCHEDULER_PRIORITY=1 --define=MODEL=mcb_bldc_sixstep_f28069mLaunchPad_openLoop --define=NUMST=1 --define=NCSTATES=0 --define=HAVESTDIO --define=MODEL_HAS_DYNAMICALLY_LOADED_SFCNS=0 --define=CLASSIC_INTERFACE=0 --define=ALLOCATIONFCN=0 --define=TID01EQ=0 --define=TERMFCN=1 --define=ONESTEPFCN=1 --define=MAT_FILE=0 --define=MULTI_INSTANCE_CODE=0 --define=INTEGER_CODE=0 --define=MT=0 --define=XCP_CUSTOM_PLATFORM --define=EXTMODE_DISABLE_ARGS_PROCESSING=1 --define=MW_PIL_SCIFIFOLEN=4 --define=MW_F2806X --define=STACK_SIZE=1024 --define=__MW_TARGET_USE_HARDWARE_RESOURCES_H__ --define=RT --define=F28069M --define=CPU1 --define=BOOT_FROM_FLASH=1 --define=MW_FAST_RTS_INCLUDED=0 --define=MW_HCCAL_INCLUDED=0 --abi=coffabi -s -v28 -ml --abi=coffabi  --preproc_dependency=$(@:%.obj=%.dep) --preproc_with_compile  --large_memory_model -I$(F28_HEADERS)/include -I$(TI_INCLUDE) -v28 -ml --float_support=fpu32 -DF28069M -DCPU1 -DBOOT_FROM_FLASH=1 --preproc_with_compile --preproc_dependency="$(basename $(<F)).d_raw" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: "$<"'
	@echo ' '

MW_c28xx_board.obj: E:/GiaotrinhDH/DATN/exampleSixStep/mcb_bldc_sixstep_f28069mLaunchPad_openLoop_ert_rtw/MW_c28xx_board.c $(GEN_OPTS) | $(GEN_FILES) $(GEN_MISC_FILES)
	@echo 'Building file: "$<"'
	@echo 'Invoking: C2000 Compiler'
	"D:/TiC2000_Install/CCS/ccs/tools/compiler/ti-cgt-c2000_22.6.0.LTS/bin/cl2000" --include_path="D:/TiC2000_Install/CCS/ccs/tools/compiler/ti-cgt-c2000_22.6.0.LTS/include" --include_path="E:/GiaotrinhDH/DATN/exampleSixStep" --include_path="C:/Program Files/MATLAB/R2023b/toolbox/c2b/tic2000/inc" --include_path="E:/GiaotrinhDH/DATN/exampleSixStep/mcb_bldc_sixstep_f28069mLaunchPad_openLoop_ert_rtw" --include_path="C:/Program Files/MATLAB/R2023b/extern/include" --include_path="C:/Program Files/MATLAB/R2023b/simulink/include" --include_path="C:/Program Files/MATLAB/R2023b/rtw/c/src" --include_path="C:/Program Files/MATLAB/R2023b/rtw/c/src/ext_mode/common" --include_path="C:/Program Files/MATLAB/R2023b/rtw/c/ert" --include_path="C:/Program Files/MATLAB/R2023b/toolbox/c2b/tic2000/src" --include_path="C:/Program Files/MATLAB/R2023b/toolbox/c2b/tic2000_shared/src" --include_path="C:/Program Files/MATLAB/R2023b/toolbox/c2b/tic2000_shared/inc" --include_path="D:/TiC2000_Install/ControlSUITE/controlSUITE/device_support/f2806x/v151/F2806x_common/include" --include_path="D:/TiC2000_Install/ControlSUITE/controlSUITE/device_support/f2806x/v151/F2806x_headers/include" --include_path="D:/TiC2000_Install/ControlSUITE/controlSUITE/libs/math/CLAmath/v400/include" --include_path="D:/TiC2000_Install/ControlSUITE/controlSUITE/libs/math/IQmath/v160/include" --include_path="C:/Program Files/MATLAB/R2023b/toolbox/shared/can/src/scanutil" --include_path="D:/TiC2000_Install/ControlSUITE/controlSUITE/libs/utilities/hrcap_hccal/type0/v110/include" --include_path="C:/Program Files/MATLAB/R2023b/toolbox/c2b/tic2000_soc/src/ipclite" --include_path="C:/Program Files/MATLAB/R2023b/toolbox/c2b/tic2000_soc/inc/ipclite" --define=MW_SCHEDULER_PRIORITY=1 --define=MODEL=mcb_bldc_sixstep_f28069mLaunchPad_openLoop --define=NUMST=1 --define=NCSTATES=0 --define=HAVESTDIO --define=MODEL_HAS_DYNAMICALLY_LOADED_SFCNS=0 --define=CLASSIC_INTERFACE=0 --define=ALLOCATIONFCN=0 --define=TID01EQ=0 --define=TERMFCN=1 --define=ONESTEPFCN=1 --define=MAT_FILE=0 --define=MULTI_INSTANCE_CODE=0 --define=INTEGER_CODE=0 --define=MT=0 --define=XCP_CUSTOM_PLATFORM --define=EXTMODE_DISABLE_ARGS_PROCESSING=1 --define=MW_PIL_SCIFIFOLEN=4 --define=MW_F2806X --define=STACK_SIZE=1024 --define=__MW_TARGET_USE_HARDWARE_RESOURCES_H__ --define=RT --define=F28069M --define=CPU1 --define=BOOT_FROM_FLASH=1 --define=MW_FAST_RTS_INCLUDED=0 --define=MW_HCCAL_INCLUDED=0 --abi=coffabi -s -v28 -ml --abi=coffabi  --preproc_dependency=$(@:%.obj=%.dep) --preproc_with_compile  --large_memory_model -I$(F28_HEADERS)/include -I$(TI_INCLUDE) -v28 -ml --float_support=fpu32 -DF28069M -DCPU1 -DBOOT_FROM_FLASH=1 --preproc_with_compile --preproc_dependency="$(basename $(<F)).d_raw" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: "$<"'
	@echo ' '

MW_c28xx_csl.obj: E:/GiaotrinhDH/DATN/exampleSixStep/mcb_bldc_sixstep_f28069mLaunchPad_openLoop_ert_rtw/MW_c28xx_csl.c $(GEN_OPTS) | $(GEN_FILES) $(GEN_MISC_FILES)
	@echo 'Building file: "$<"'
	@echo 'Invoking: C2000 Compiler'
	"D:/TiC2000_Install/CCS/ccs/tools/compiler/ti-cgt-c2000_22.6.0.LTS/bin/cl2000" --include_path="D:/TiC2000_Install/CCS/ccs/tools/compiler/ti-cgt-c2000_22.6.0.LTS/include" --include_path="E:/GiaotrinhDH/DATN/exampleSixStep" --include_path="C:/Program Files/MATLAB/R2023b/toolbox/c2b/tic2000/inc" --include_path="E:/GiaotrinhDH/DATN/exampleSixStep/mcb_bldc_sixstep_f28069mLaunchPad_openLoop_ert_rtw" --include_path="C:/Program Files/MATLAB/R2023b/extern/include" --include_path="C:/Program Files/MATLAB/R2023b/simulink/include" --include_path="C:/Program Files/MATLAB/R2023b/rtw/c/src" --include_path="C:/Program Files/MATLAB/R2023b/rtw/c/src/ext_mode/common" --include_path="C:/Program Files/MATLAB/R2023b/rtw/c/ert" --include_path="C:/Program Files/MATLAB/R2023b/toolbox/c2b/tic2000/src" --include_path="C:/Program Files/MATLAB/R2023b/toolbox/c2b/tic2000_shared/src" --include_path="C:/Program Files/MATLAB/R2023b/toolbox/c2b/tic2000_shared/inc" --include_path="D:/TiC2000_Install/ControlSUITE/controlSUITE/device_support/f2806x/v151/F2806x_common/include" --include_path="D:/TiC2000_Install/ControlSUITE/controlSUITE/device_support/f2806x/v151/F2806x_headers/include" --include_path="D:/TiC2000_Install/ControlSUITE/controlSUITE/libs/math/CLAmath/v400/include" --include_path="D:/TiC2000_Install/ControlSUITE/controlSUITE/libs/math/IQmath/v160/include" --include_path="C:/Program Files/MATLAB/R2023b/toolbox/shared/can/src/scanutil" --include_path="D:/TiC2000_Install/ControlSUITE/controlSUITE/libs/utilities/hrcap_hccal/type0/v110/include" --include_path="C:/Program Files/MATLAB/R2023b/toolbox/c2b/tic2000_soc/src/ipclite" --include_path="C:/Program Files/MATLAB/R2023b/toolbox/c2b/tic2000_soc/inc/ipclite" --define=MW_SCHEDULER_PRIORITY=1 --define=MODEL=mcb_bldc_sixstep_f28069mLaunchPad_openLoop --define=NUMST=1 --define=NCSTATES=0 --define=HAVESTDIO --define=MODEL_HAS_DYNAMICALLY_LOADED_SFCNS=0 --define=CLASSIC_INTERFACE=0 --define=ALLOCATIONFCN=0 --define=TID01EQ=0 --define=TERMFCN=1 --define=ONESTEPFCN=1 --define=MAT_FILE=0 --define=MULTI_INSTANCE_CODE=0 --define=INTEGER_CODE=0 --define=MT=0 --define=XCP_CUSTOM_PLATFORM --define=EXTMODE_DISABLE_ARGS_PROCESSING=1 --define=MW_PIL_SCIFIFOLEN=4 --define=MW_F2806X --define=STACK_SIZE=1024 --define=__MW_TARGET_USE_HARDWARE_RESOURCES_H__ --define=RT --define=F28069M --define=CPU1 --define=BOOT_FROM_FLASH=1 --define=MW_FAST_RTS_INCLUDED=0 --define=MW_HCCAL_INCLUDED=0 --abi=coffabi -s -v28 -ml --abi=coffabi  --preproc_dependency=$(@:%.obj=%.dep) --preproc_with_compile  --large_memory_model -I$(F28_HEADERS)/include -I$(TI_INCLUDE) -v28 -ml --float_support=fpu32 -DF28069M -DCPU1 -DBOOT_FROM_FLASH=1 --preproc_with_compile --preproc_dependency="$(basename $(<F)).d_raw" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: "$<"'
	@echo ' '

MW_c28xx_pwm.obj: E:/GiaotrinhDH/DATN/exampleSixStep/mcb_bldc_sixstep_f28069mLaunchPad_openLoop_ert_rtw/MW_c28xx_pwm.c $(GEN_OPTS) | $(GEN_FILES) $(GEN_MISC_FILES)
	@echo 'Building file: "$<"'
	@echo 'Invoking: C2000 Compiler'
	"D:/TiC2000_Install/CCS/ccs/tools/compiler/ti-cgt-c2000_22.6.0.LTS/bin/cl2000" --include_path="D:/TiC2000_Install/CCS/ccs/tools/compiler/ti-cgt-c2000_22.6.0.LTS/include" --include_path="E:/GiaotrinhDH/DATN/exampleSixStep" --include_path="C:/Program Files/MATLAB/R2023b/toolbox/c2b/tic2000/inc" --include_path="E:/GiaotrinhDH/DATN/exampleSixStep/mcb_bldc_sixstep_f28069mLaunchPad_openLoop_ert_rtw" --include_path="C:/Program Files/MATLAB/R2023b/extern/include" --include_path="C:/Program Files/MATLAB/R2023b/simulink/include" --include_path="C:/Program Files/MATLAB/R2023b/rtw/c/src" --include_path="C:/Program Files/MATLAB/R2023b/rtw/c/src/ext_mode/common" --include_path="C:/Program Files/MATLAB/R2023b/rtw/c/ert" --include_path="C:/Program Files/MATLAB/R2023b/toolbox/c2b/tic2000/src" --include_path="C:/Program Files/MATLAB/R2023b/toolbox/c2b/tic2000_shared/src" --include_path="C:/Program Files/MATLAB/R2023b/toolbox/c2b/tic2000_shared/inc" --include_path="D:/TiC2000_Install/ControlSUITE/controlSUITE/device_support/f2806x/v151/F2806x_common/include" --include_path="D:/TiC2000_Install/ControlSUITE/controlSUITE/device_support/f2806x/v151/F2806x_headers/include" --include_path="D:/TiC2000_Install/ControlSUITE/controlSUITE/libs/math/CLAmath/v400/include" --include_path="D:/TiC2000_Install/ControlSUITE/controlSUITE/libs/math/IQmath/v160/include" --include_path="C:/Program Files/MATLAB/R2023b/toolbox/shared/can/src/scanutil" --include_path="D:/TiC2000_Install/ControlSUITE/controlSUITE/libs/utilities/hrcap_hccal/type0/v110/include" --include_path="C:/Program Files/MATLAB/R2023b/toolbox/c2b/tic2000_soc/src/ipclite" --include_path="C:/Program Files/MATLAB/R2023b/toolbox/c2b/tic2000_soc/inc/ipclite" --define=MW_SCHEDULER_PRIORITY=1 --define=MODEL=mcb_bldc_sixstep_f28069mLaunchPad_openLoop --define=NUMST=1 --define=NCSTATES=0 --define=HAVESTDIO --define=MODEL_HAS_DYNAMICALLY_LOADED_SFCNS=0 --define=CLASSIC_INTERFACE=0 --define=ALLOCATIONFCN=0 --define=TID01EQ=0 --define=TERMFCN=1 --define=ONESTEPFCN=1 --define=MAT_FILE=0 --define=MULTI_INSTANCE_CODE=0 --define=INTEGER_CODE=0 --define=MT=0 --define=XCP_CUSTOM_PLATFORM --define=EXTMODE_DISABLE_ARGS_PROCESSING=1 --define=MW_PIL_SCIFIFOLEN=4 --define=MW_F2806X --define=STACK_SIZE=1024 --define=__MW_TARGET_USE_HARDWARE_RESOURCES_H__ --define=RT --define=F28069M --define=CPU1 --define=BOOT_FROM_FLASH=1 --define=MW_FAST_RTS_INCLUDED=0 --define=MW_HCCAL_INCLUDED=0 --abi=coffabi -s -v28 -ml --abi=coffabi  --preproc_dependency=$(@:%.obj=%.dep) --preproc_with_compile  --large_memory_model -I$(F28_HEADERS)/include -I$(TI_INCLUDE) -v28 -ml --float_support=fpu32 -DF28069M -DCPU1 -DBOOT_FROM_FLASH=1 --preproc_with_compile --preproc_dependency="$(basename $(<F)).d_raw" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: "$<"'
	@echo ' '

MW_c28xx_qep.obj: E:/GiaotrinhDH/DATN/exampleSixStep/mcb_bldc_sixstep_f28069mLaunchPad_openLoop_ert_rtw/MW_c28xx_qep.c $(GEN_OPTS) | $(GEN_FILES) $(GEN_MISC_FILES)
	@echo 'Building file: "$<"'
	@echo 'Invoking: C2000 Compiler'
	"D:/TiC2000_Install/CCS/ccs/tools/compiler/ti-cgt-c2000_22.6.0.LTS/bin/cl2000" --include_path="D:/TiC2000_Install/CCS/ccs/tools/compiler/ti-cgt-c2000_22.6.0.LTS/include" --include_path="E:/GiaotrinhDH/DATN/exampleSixStep" --include_path="C:/Program Files/MATLAB/R2023b/toolbox/c2b/tic2000/inc" --include_path="E:/GiaotrinhDH/DATN/exampleSixStep/mcb_bldc_sixstep_f28069mLaunchPad_openLoop_ert_rtw" --include_path="C:/Program Files/MATLAB/R2023b/extern/include" --include_path="C:/Program Files/MATLAB/R2023b/simulink/include" --include_path="C:/Program Files/MATLAB/R2023b/rtw/c/src" --include_path="C:/Program Files/MATLAB/R2023b/rtw/c/src/ext_mode/common" --include_path="C:/Program Files/MATLAB/R2023b/rtw/c/ert" --include_path="C:/Program Files/MATLAB/R2023b/toolbox/c2b/tic2000/src" --include_path="C:/Program Files/MATLAB/R2023b/toolbox/c2b/tic2000_shared/src" --include_path="C:/Program Files/MATLAB/R2023b/toolbox/c2b/tic2000_shared/inc" --include_path="D:/TiC2000_Install/ControlSUITE/controlSUITE/device_support/f2806x/v151/F2806x_common/include" --include_path="D:/TiC2000_Install/ControlSUITE/controlSUITE/device_support/f2806x/v151/F2806x_headers/include" --include_path="D:/TiC2000_Install/ControlSUITE/controlSUITE/libs/math/CLAmath/v400/include" --include_path="D:/TiC2000_Install/ControlSUITE/controlSUITE/libs/math/IQmath/v160/include" --include_path="C:/Program Files/MATLAB/R2023b/toolbox/shared/can/src/scanutil" --include_path="D:/TiC2000_Install/ControlSUITE/controlSUITE/libs/utilities/hrcap_hccal/type0/v110/include" --include_path="C:/Program Files/MATLAB/R2023b/toolbox/c2b/tic2000_soc/src/ipclite" --include_path="C:/Program Files/MATLAB/R2023b/toolbox/c2b/tic2000_soc/inc/ipclite" --define=MW_SCHEDULER_PRIORITY=1 --define=MODEL=mcb_bldc_sixstep_f28069mLaunchPad_openLoop --define=NUMST=1 --define=NCSTATES=0 --define=HAVESTDIO --define=MODEL_HAS_DYNAMICALLY_LOADED_SFCNS=0 --define=CLASSIC_INTERFACE=0 --define=ALLOCATIONFCN=0 --define=TID01EQ=0 --define=TERMFCN=1 --define=ONESTEPFCN=1 --define=MAT_FILE=0 --define=MULTI_INSTANCE_CODE=0 --define=INTEGER_CODE=0 --define=MT=0 --define=XCP_CUSTOM_PLATFORM --define=EXTMODE_DISABLE_ARGS_PROCESSING=1 --define=MW_PIL_SCIFIFOLEN=4 --define=MW_F2806X --define=STACK_SIZE=1024 --define=__MW_TARGET_USE_HARDWARE_RESOURCES_H__ --define=RT --define=F28069M --define=CPU1 --define=BOOT_FROM_FLASH=1 --define=MW_FAST_RTS_INCLUDED=0 --define=MW_HCCAL_INCLUDED=0 --abi=coffabi -s -v28 -ml --abi=coffabi  --preproc_dependency=$(@:%.obj=%.dep) --preproc_with_compile  --large_memory_model -I$(F28_HEADERS)/include -I$(TI_INCLUDE) -v28 -ml --float_support=fpu32 -DF28069M -DCPU1 -DBOOT_FROM_FLASH=1 --preproc_with_compile --preproc_dependency="$(basename $(<F)).d_raw" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: "$<"'
	@echo ' '

blapp_support.obj: C:/Program\ Files/MATLAB/R2023b/toolbox/c2b/tic2000/src/blapp_support.c $(GEN_OPTS) | $(GEN_FILES) $(GEN_MISC_FILES)
	@echo 'Building file: "$<"'
	@echo 'Invoking: C2000 Compiler'
	"D:/TiC2000_Install/CCS/ccs/tools/compiler/ti-cgt-c2000_22.6.0.LTS/bin/cl2000" --include_path="D:/TiC2000_Install/CCS/ccs/tools/compiler/ti-cgt-c2000_22.6.0.LTS/include" --include_path="E:/GiaotrinhDH/DATN/exampleSixStep" --include_path="C:/Program Files/MATLAB/R2023b/toolbox/c2b/tic2000/inc" --include_path="E:/GiaotrinhDH/DATN/exampleSixStep/mcb_bldc_sixstep_f28069mLaunchPad_openLoop_ert_rtw" --include_path="C:/Program Files/MATLAB/R2023b/extern/include" --include_path="C:/Program Files/MATLAB/R2023b/simulink/include" --include_path="C:/Program Files/MATLAB/R2023b/rtw/c/src" --include_path="C:/Program Files/MATLAB/R2023b/rtw/c/src/ext_mode/common" --include_path="C:/Program Files/MATLAB/R2023b/rtw/c/ert" --include_path="C:/Program Files/MATLAB/R2023b/toolbox/c2b/tic2000/src" --include_path="C:/Program Files/MATLAB/R2023b/toolbox/c2b/tic2000_shared/src" --include_path="C:/Program Files/MATLAB/R2023b/toolbox/c2b/tic2000_shared/inc" --include_path="D:/TiC2000_Install/ControlSUITE/controlSUITE/device_support/f2806x/v151/F2806x_common/include" --include_path="D:/TiC2000_Install/ControlSUITE/controlSUITE/device_support/f2806x/v151/F2806x_headers/include" --include_path="D:/TiC2000_Install/ControlSUITE/controlSUITE/libs/math/CLAmath/v400/include" --include_path="D:/TiC2000_Install/ControlSUITE/controlSUITE/libs/math/IQmath/v160/include" --include_path="C:/Program Files/MATLAB/R2023b/toolbox/shared/can/src/scanutil" --include_path="D:/TiC2000_Install/ControlSUITE/controlSUITE/libs/utilities/hrcap_hccal/type0/v110/include" --include_path="C:/Program Files/MATLAB/R2023b/toolbox/c2b/tic2000_soc/src/ipclite" --include_path="C:/Program Files/MATLAB/R2023b/toolbox/c2b/tic2000_soc/inc/ipclite" --define=MW_SCHEDULER_PRIORITY=1 --define=MODEL=mcb_bldc_sixstep_f28069mLaunchPad_openLoop --define=NUMST=1 --define=NCSTATES=0 --define=HAVESTDIO --define=MODEL_HAS_DYNAMICALLY_LOADED_SFCNS=0 --define=CLASSIC_INTERFACE=0 --define=ALLOCATIONFCN=0 --define=TID01EQ=0 --define=TERMFCN=1 --define=ONESTEPFCN=1 --define=MAT_FILE=0 --define=MULTI_INSTANCE_CODE=0 --define=INTEGER_CODE=0 --define=MT=0 --define=XCP_CUSTOM_PLATFORM --define=EXTMODE_DISABLE_ARGS_PROCESSING=1 --define=MW_PIL_SCIFIFOLEN=4 --define=MW_F2806X --define=STACK_SIZE=1024 --define=__MW_TARGET_USE_HARDWARE_RESOURCES_H__ --define=RT --define=F28069M --define=CPU1 --define=BOOT_FROM_FLASH=1 --define=MW_FAST_RTS_INCLUDED=0 --define=MW_HCCAL_INCLUDED=0 --abi=coffabi -s -v28 -ml --abi=coffabi  --preproc_dependency=$(@:%.obj=%.dep) --preproc_with_compile  --large_memory_model -I$(F28_HEADERS)/include -I$(TI_INCLUDE) -v28 -ml --float_support=fpu32 -DF28069M -DCPU1 -DBOOT_FROM_FLASH=1 --preproc_with_compile --preproc_dependency="$(basename $(<F)).d_raw" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: "$<"'
	@echo ' '

c2000HardwareTimerConfig.obj: C:/Program\ Files/MATLAB/R2023b/toolbox/c2b/tic2000/src/c2000HardwareTimerConfig.c $(GEN_OPTS) | $(GEN_FILES) $(GEN_MISC_FILES)
	@echo 'Building file: "$<"'
	@echo 'Invoking: C2000 Compiler'
	"D:/TiC2000_Install/CCS/ccs/tools/compiler/ti-cgt-c2000_22.6.0.LTS/bin/cl2000" --include_path="D:/TiC2000_Install/CCS/ccs/tools/compiler/ti-cgt-c2000_22.6.0.LTS/include" --include_path="E:/GiaotrinhDH/DATN/exampleSixStep" --include_path="C:/Program Files/MATLAB/R2023b/toolbox/c2b/tic2000/inc" --include_path="E:/GiaotrinhDH/DATN/exampleSixStep/mcb_bldc_sixstep_f28069mLaunchPad_openLoop_ert_rtw" --include_path="C:/Program Files/MATLAB/R2023b/extern/include" --include_path="C:/Program Files/MATLAB/R2023b/simulink/include" --include_path="C:/Program Files/MATLAB/R2023b/rtw/c/src" --include_path="C:/Program Files/MATLAB/R2023b/rtw/c/src/ext_mode/common" --include_path="C:/Program Files/MATLAB/R2023b/rtw/c/ert" --include_path="C:/Program Files/MATLAB/R2023b/toolbox/c2b/tic2000/src" --include_path="C:/Program Files/MATLAB/R2023b/toolbox/c2b/tic2000_shared/src" --include_path="C:/Program Files/MATLAB/R2023b/toolbox/c2b/tic2000_shared/inc" --include_path="D:/TiC2000_Install/ControlSUITE/controlSUITE/device_support/f2806x/v151/F2806x_common/include" --include_path="D:/TiC2000_Install/ControlSUITE/controlSUITE/device_support/f2806x/v151/F2806x_headers/include" --include_path="D:/TiC2000_Install/ControlSUITE/controlSUITE/libs/math/CLAmath/v400/include" --include_path="D:/TiC2000_Install/ControlSUITE/controlSUITE/libs/math/IQmath/v160/include" --include_path="C:/Program Files/MATLAB/R2023b/toolbox/shared/can/src/scanutil" --include_path="D:/TiC2000_Install/ControlSUITE/controlSUITE/libs/utilities/hrcap_hccal/type0/v110/include" --include_path="C:/Program Files/MATLAB/R2023b/toolbox/c2b/tic2000_soc/src/ipclite" --include_path="C:/Program Files/MATLAB/R2023b/toolbox/c2b/tic2000_soc/inc/ipclite" --define=MW_SCHEDULER_PRIORITY=1 --define=MODEL=mcb_bldc_sixstep_f28069mLaunchPad_openLoop --define=NUMST=1 --define=NCSTATES=0 --define=HAVESTDIO --define=MODEL_HAS_DYNAMICALLY_LOADED_SFCNS=0 --define=CLASSIC_INTERFACE=0 --define=ALLOCATIONFCN=0 --define=TID01EQ=0 --define=TERMFCN=1 --define=ONESTEPFCN=1 --define=MAT_FILE=0 --define=MULTI_INSTANCE_CODE=0 --define=INTEGER_CODE=0 --define=MT=0 --define=XCP_CUSTOM_PLATFORM --define=EXTMODE_DISABLE_ARGS_PROCESSING=1 --define=MW_PIL_SCIFIFOLEN=4 --define=MW_F2806X --define=STACK_SIZE=1024 --define=__MW_TARGET_USE_HARDWARE_RESOURCES_H__ --define=RT --define=F28069M --define=CPU1 --define=BOOT_FROM_FLASH=1 --define=MW_FAST_RTS_INCLUDED=0 --define=MW_HCCAL_INCLUDED=0 --abi=coffabi -s -v28 -ml --abi=coffabi  --preproc_dependency=$(@:%.obj=%.dep) --preproc_with_compile  --large_memory_model -I$(F28_HEADERS)/include -I$(TI_INCLUDE) -v28 -ml --float_support=fpu32 -DF28069M -DCPU1 -DBOOT_FROM_FLASH=1 --preproc_with_compile --preproc_dependency="$(basename $(<F)).d_raw" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: "$<"'
	@echo ' '

c2806xBoard_Realtime_Support.obj: C:/Program\ Files/MATLAB/R2023b/toolbox/c2b/tic2000/src/c2806xBoard_Realtime_Support.c $(GEN_OPTS) | $(GEN_FILES) $(GEN_MISC_FILES)
	@echo 'Building file: "$<"'
	@echo 'Invoking: C2000 Compiler'
	"D:/TiC2000_Install/CCS/ccs/tools/compiler/ti-cgt-c2000_22.6.0.LTS/bin/cl2000" --include_path="D:/TiC2000_Install/CCS/ccs/tools/compiler/ti-cgt-c2000_22.6.0.LTS/include" --include_path="E:/GiaotrinhDH/DATN/exampleSixStep" --include_path="C:/Program Files/MATLAB/R2023b/toolbox/c2b/tic2000/inc" --include_path="E:/GiaotrinhDH/DATN/exampleSixStep/mcb_bldc_sixstep_f28069mLaunchPad_openLoop_ert_rtw" --include_path="C:/Program Files/MATLAB/R2023b/extern/include" --include_path="C:/Program Files/MATLAB/R2023b/simulink/include" --include_path="C:/Program Files/MATLAB/R2023b/rtw/c/src" --include_path="C:/Program Files/MATLAB/R2023b/rtw/c/src/ext_mode/common" --include_path="C:/Program Files/MATLAB/R2023b/rtw/c/ert" --include_path="C:/Program Files/MATLAB/R2023b/toolbox/c2b/tic2000/src" --include_path="C:/Program Files/MATLAB/R2023b/toolbox/c2b/tic2000_shared/src" --include_path="C:/Program Files/MATLAB/R2023b/toolbox/c2b/tic2000_shared/inc" --include_path="D:/TiC2000_Install/ControlSUITE/controlSUITE/device_support/f2806x/v151/F2806x_common/include" --include_path="D:/TiC2000_Install/ControlSUITE/controlSUITE/device_support/f2806x/v151/F2806x_headers/include" --include_path="D:/TiC2000_Install/ControlSUITE/controlSUITE/libs/math/CLAmath/v400/include" --include_path="D:/TiC2000_Install/ControlSUITE/controlSUITE/libs/math/IQmath/v160/include" --include_path="C:/Program Files/MATLAB/R2023b/toolbox/shared/can/src/scanutil" --include_path="D:/TiC2000_Install/ControlSUITE/controlSUITE/libs/utilities/hrcap_hccal/type0/v110/include" --include_path="C:/Program Files/MATLAB/R2023b/toolbox/c2b/tic2000_soc/src/ipclite" --include_path="C:/Program Files/MATLAB/R2023b/toolbox/c2b/tic2000_soc/inc/ipclite" --define=MW_SCHEDULER_PRIORITY=1 --define=MODEL=mcb_bldc_sixstep_f28069mLaunchPad_openLoop --define=NUMST=1 --define=NCSTATES=0 --define=HAVESTDIO --define=MODEL_HAS_DYNAMICALLY_LOADED_SFCNS=0 --define=CLASSIC_INTERFACE=0 --define=ALLOCATIONFCN=0 --define=TID01EQ=0 --define=TERMFCN=1 --define=ONESTEPFCN=1 --define=MAT_FILE=0 --define=MULTI_INSTANCE_CODE=0 --define=INTEGER_CODE=0 --define=MT=0 --define=XCP_CUSTOM_PLATFORM --define=EXTMODE_DISABLE_ARGS_PROCESSING=1 --define=MW_PIL_SCIFIFOLEN=4 --define=MW_F2806X --define=STACK_SIZE=1024 --define=__MW_TARGET_USE_HARDWARE_RESOURCES_H__ --define=RT --define=F28069M --define=CPU1 --define=BOOT_FROM_FLASH=1 --define=MW_FAST_RTS_INCLUDED=0 --define=MW_HCCAL_INCLUDED=0 --abi=coffabi -s -v28 -ml --abi=coffabi  --preproc_dependency=$(@:%.obj=%.dep) --preproc_with_compile  --large_memory_model -I$(F28_HEADERS)/include -I$(TI_INCLUDE) -v28 -ml --float_support=fpu32 -DF28069M -DCPU1 -DBOOT_FROM_FLASH=1 --preproc_with_compile --preproc_dependency="$(basename $(<F)).d_raw" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: "$<"'
	@echo ' '

c2806xSchedulerTimer0.obj: C:/Program\ Files/MATLAB/R2023b/toolbox/c2b/tic2000/src/c2806xSchedulerTimer0.c $(GEN_OPTS) | $(GEN_FILES) $(GEN_MISC_FILES)
	@echo 'Building file: "$<"'
	@echo 'Invoking: C2000 Compiler'
	"D:/TiC2000_Install/CCS/ccs/tools/compiler/ti-cgt-c2000_22.6.0.LTS/bin/cl2000" --include_path="D:/TiC2000_Install/CCS/ccs/tools/compiler/ti-cgt-c2000_22.6.0.LTS/include" --include_path="E:/GiaotrinhDH/DATN/exampleSixStep" --include_path="C:/Program Files/MATLAB/R2023b/toolbox/c2b/tic2000/inc" --include_path="E:/GiaotrinhDH/DATN/exampleSixStep/mcb_bldc_sixstep_f28069mLaunchPad_openLoop_ert_rtw" --include_path="C:/Program Files/MATLAB/R2023b/extern/include" --include_path="C:/Program Files/MATLAB/R2023b/simulink/include" --include_path="C:/Program Files/MATLAB/R2023b/rtw/c/src" --include_path="C:/Program Files/MATLAB/R2023b/rtw/c/src/ext_mode/common" --include_path="C:/Program Files/MATLAB/R2023b/rtw/c/ert" --include_path="C:/Program Files/MATLAB/R2023b/toolbox/c2b/tic2000/src" --include_path="C:/Program Files/MATLAB/R2023b/toolbox/c2b/tic2000_shared/src" --include_path="C:/Program Files/MATLAB/R2023b/toolbox/c2b/tic2000_shared/inc" --include_path="D:/TiC2000_Install/ControlSUITE/controlSUITE/device_support/f2806x/v151/F2806x_common/include" --include_path="D:/TiC2000_Install/ControlSUITE/controlSUITE/device_support/f2806x/v151/F2806x_headers/include" --include_path="D:/TiC2000_Install/ControlSUITE/controlSUITE/libs/math/CLAmath/v400/include" --include_path="D:/TiC2000_Install/ControlSUITE/controlSUITE/libs/math/IQmath/v160/include" --include_path="C:/Program Files/MATLAB/R2023b/toolbox/shared/can/src/scanutil" --include_path="D:/TiC2000_Install/ControlSUITE/controlSUITE/libs/utilities/hrcap_hccal/type0/v110/include" --include_path="C:/Program Files/MATLAB/R2023b/toolbox/c2b/tic2000_soc/src/ipclite" --include_path="C:/Program Files/MATLAB/R2023b/toolbox/c2b/tic2000_soc/inc/ipclite" --define=MW_SCHEDULER_PRIORITY=1 --define=MODEL=mcb_bldc_sixstep_f28069mLaunchPad_openLoop --define=NUMST=1 --define=NCSTATES=0 --define=HAVESTDIO --define=MODEL_HAS_DYNAMICALLY_LOADED_SFCNS=0 --define=CLASSIC_INTERFACE=0 --define=ALLOCATIONFCN=0 --define=TID01EQ=0 --define=TERMFCN=1 --define=ONESTEPFCN=1 --define=MAT_FILE=0 --define=MULTI_INSTANCE_CODE=0 --define=INTEGER_CODE=0 --define=MT=0 --define=XCP_CUSTOM_PLATFORM --define=EXTMODE_DISABLE_ARGS_PROCESSING=1 --define=MW_PIL_SCIFIFOLEN=4 --define=MW_F2806X --define=STACK_SIZE=1024 --define=__MW_TARGET_USE_HARDWARE_RESOURCES_H__ --define=RT --define=F28069M --define=CPU1 --define=BOOT_FROM_FLASH=1 --define=MW_FAST_RTS_INCLUDED=0 --define=MW_HCCAL_INCLUDED=0 --abi=coffabi -s -v28 -ml --abi=coffabi  --preproc_dependency=$(@:%.obj=%.dep) --preproc_with_compile  --large_memory_model -I$(F28_HEADERS)/include -I$(TI_INCLUDE) -v28 -ml --float_support=fpu32 -DF28069M -DCPU1 -DBOOT_FROM_FLASH=1 --preproc_with_compile --preproc_dependency="$(basename $(<F)).d_raw" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: "$<"'
	@echo ' '

ert_main.obj: E:/GiaotrinhDH/DATN/exampleSixStep/mcb_bldc_sixstep_f28069mLaunchPad_openLoop_ert_rtw/ert_main.c $(GEN_OPTS) | $(GEN_FILES) $(GEN_MISC_FILES)
	@echo 'Building file: "$<"'
	@echo 'Invoking: C2000 Compiler'
	"D:/TiC2000_Install/CCS/ccs/tools/compiler/ti-cgt-c2000_22.6.0.LTS/bin/cl2000" --include_path="D:/TiC2000_Install/CCS/ccs/tools/compiler/ti-cgt-c2000_22.6.0.LTS/include" --include_path="E:/GiaotrinhDH/DATN/exampleSixStep" --include_path="C:/Program Files/MATLAB/R2023b/toolbox/c2b/tic2000/inc" --include_path="E:/GiaotrinhDH/DATN/exampleSixStep/mcb_bldc_sixstep_f28069mLaunchPad_openLoop_ert_rtw" --include_path="C:/Program Files/MATLAB/R2023b/extern/include" --include_path="C:/Program Files/MATLAB/R2023b/simulink/include" --include_path="C:/Program Files/MATLAB/R2023b/rtw/c/src" --include_path="C:/Program Files/MATLAB/R2023b/rtw/c/src/ext_mode/common" --include_path="C:/Program Files/MATLAB/R2023b/rtw/c/ert" --include_path="C:/Program Files/MATLAB/R2023b/toolbox/c2b/tic2000/src" --include_path="C:/Program Files/MATLAB/R2023b/toolbox/c2b/tic2000_shared/src" --include_path="C:/Program Files/MATLAB/R2023b/toolbox/c2b/tic2000_shared/inc" --include_path="D:/TiC2000_Install/ControlSUITE/controlSUITE/device_support/f2806x/v151/F2806x_common/include" --include_path="D:/TiC2000_Install/ControlSUITE/controlSUITE/device_support/f2806x/v151/F2806x_headers/include" --include_path="D:/TiC2000_Install/ControlSUITE/controlSUITE/libs/math/CLAmath/v400/include" --include_path="D:/TiC2000_Install/ControlSUITE/controlSUITE/libs/math/IQmath/v160/include" --include_path="C:/Program Files/MATLAB/R2023b/toolbox/shared/can/src/scanutil" --include_path="D:/TiC2000_Install/ControlSUITE/controlSUITE/libs/utilities/hrcap_hccal/type0/v110/include" --include_path="C:/Program Files/MATLAB/R2023b/toolbox/c2b/tic2000_soc/src/ipclite" --include_path="C:/Program Files/MATLAB/R2023b/toolbox/c2b/tic2000_soc/inc/ipclite" --define=MW_SCHEDULER_PRIORITY=1 --define=MODEL=mcb_bldc_sixstep_f28069mLaunchPad_openLoop --define=NUMST=1 --define=NCSTATES=0 --define=HAVESTDIO --define=MODEL_HAS_DYNAMICALLY_LOADED_SFCNS=0 --define=CLASSIC_INTERFACE=0 --define=ALLOCATIONFCN=0 --define=TID01EQ=0 --define=TERMFCN=1 --define=ONESTEPFCN=1 --define=MAT_FILE=0 --define=MULTI_INSTANCE_CODE=0 --define=INTEGER_CODE=0 --define=MT=0 --define=XCP_CUSTOM_PLATFORM --define=EXTMODE_DISABLE_ARGS_PROCESSING=1 --define=MW_PIL_SCIFIFOLEN=4 --define=MW_F2806X --define=STACK_SIZE=1024 --define=__MW_TARGET_USE_HARDWARE_RESOURCES_H__ --define=RT --define=F28069M --define=CPU1 --define=BOOT_FROM_FLASH=1 --define=MW_FAST_RTS_INCLUDED=0 --define=MW_HCCAL_INCLUDED=0 --abi=coffabi -s -v28 -ml --abi=coffabi  --preproc_dependency=$(@:%.obj=%.dep) --preproc_with_compile  --large_memory_model -I$(F28_HEADERS)/include -I$(TI_INCLUDE) -v28 -ml --float_support=fpu32 -DF28069M -DCPU1 -DBOOT_FROM_FLASH=1 --preproc_with_compile --preproc_dependency="$(basename $(<F)).d_raw" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: "$<"'
	@echo ' '

mcb_bldc_sixstep_f28069mLaunchPad_openLoop.obj: E:/GiaotrinhDH/DATN/exampleSixStep/mcb_bldc_sixstep_f28069mLaunchPad_openLoop_ert_rtw/mcb_bldc_sixstep_f28069mLaunchPad_openLoop.c $(GEN_OPTS) | $(GEN_FILES) $(GEN_MISC_FILES)
	@echo 'Building file: "$<"'
	@echo 'Invoking: C2000 Compiler'
	"D:/TiC2000_Install/CCS/ccs/tools/compiler/ti-cgt-c2000_22.6.0.LTS/bin/cl2000" --include_path="D:/TiC2000_Install/CCS/ccs/tools/compiler/ti-cgt-c2000_22.6.0.LTS/include" --include_path="E:/GiaotrinhDH/DATN/exampleSixStep" --include_path="C:/Program Files/MATLAB/R2023b/toolbox/c2b/tic2000/inc" --include_path="E:/GiaotrinhDH/DATN/exampleSixStep/mcb_bldc_sixstep_f28069mLaunchPad_openLoop_ert_rtw" --include_path="C:/Program Files/MATLAB/R2023b/extern/include" --include_path="C:/Program Files/MATLAB/R2023b/simulink/include" --include_path="C:/Program Files/MATLAB/R2023b/rtw/c/src" --include_path="C:/Program Files/MATLAB/R2023b/rtw/c/src/ext_mode/common" --include_path="C:/Program Files/MATLAB/R2023b/rtw/c/ert" --include_path="C:/Program Files/MATLAB/R2023b/toolbox/c2b/tic2000/src" --include_path="C:/Program Files/MATLAB/R2023b/toolbox/c2b/tic2000_shared/src" --include_path="C:/Program Files/MATLAB/R2023b/toolbox/c2b/tic2000_shared/inc" --include_path="D:/TiC2000_Install/ControlSUITE/controlSUITE/device_support/f2806x/v151/F2806x_common/include" --include_path="D:/TiC2000_Install/ControlSUITE/controlSUITE/device_support/f2806x/v151/F2806x_headers/include" --include_path="D:/TiC2000_Install/ControlSUITE/controlSUITE/libs/math/CLAmath/v400/include" --include_path="D:/TiC2000_Install/ControlSUITE/controlSUITE/libs/math/IQmath/v160/include" --include_path="C:/Program Files/MATLAB/R2023b/toolbox/shared/can/src/scanutil" --include_path="D:/TiC2000_Install/ControlSUITE/controlSUITE/libs/utilities/hrcap_hccal/type0/v110/include" --include_path="C:/Program Files/MATLAB/R2023b/toolbox/c2b/tic2000_soc/src/ipclite" --include_path="C:/Program Files/MATLAB/R2023b/toolbox/c2b/tic2000_soc/inc/ipclite" --define=MW_SCHEDULER_PRIORITY=1 --define=MODEL=mcb_bldc_sixstep_f28069mLaunchPad_openLoop --define=NUMST=1 --define=NCSTATES=0 --define=HAVESTDIO --define=MODEL_HAS_DYNAMICALLY_LOADED_SFCNS=0 --define=CLASSIC_INTERFACE=0 --define=ALLOCATIONFCN=0 --define=TID01EQ=0 --define=TERMFCN=1 --define=ONESTEPFCN=1 --define=MAT_FILE=0 --define=MULTI_INSTANCE_CODE=0 --define=INTEGER_CODE=0 --define=MT=0 --define=XCP_CUSTOM_PLATFORM --define=EXTMODE_DISABLE_ARGS_PROCESSING=1 --define=MW_PIL_SCIFIFOLEN=4 --define=MW_F2806X --define=STACK_SIZE=1024 --define=__MW_TARGET_USE_HARDWARE_RESOURCES_H__ --define=RT --define=F28069M --define=CPU1 --define=BOOT_FROM_FLASH=1 --define=MW_FAST_RTS_INCLUDED=0 --define=MW_HCCAL_INCLUDED=0 --abi=coffabi -s -v28 -ml --abi=coffabi  --preproc_dependency=$(@:%.obj=%.dep) --preproc_with_compile  --large_memory_model -I$(F28_HEADERS)/include -I$(TI_INCLUDE) -v28 -ml --float_support=fpu32 -DF28069M -DCPU1 -DBOOT_FROM_FLASH=1 --preproc_with_compile --preproc_dependency="$(basename $(<F)).d_raw" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: "$<"'
	@echo ' '

mcb_bldc_sixstep_f28069mLaunchPad_openLoop_data.obj: E:/GiaotrinhDH/DATN/exampleSixStep/mcb_bldc_sixstep_f28069mLaunchPad_openLoop_ert_rtw/mcb_bldc_sixstep_f28069mLaunchPad_openLoop_data.c $(GEN_OPTS) | $(GEN_FILES) $(GEN_MISC_FILES)
	@echo 'Building file: "$<"'
	@echo 'Invoking: C2000 Compiler'
	"D:/TiC2000_Install/CCS/ccs/tools/compiler/ti-cgt-c2000_22.6.0.LTS/bin/cl2000" --include_path="D:/TiC2000_Install/CCS/ccs/tools/compiler/ti-cgt-c2000_22.6.0.LTS/include" --include_path="E:/GiaotrinhDH/DATN/exampleSixStep" --include_path="C:/Program Files/MATLAB/R2023b/toolbox/c2b/tic2000/inc" --include_path="E:/GiaotrinhDH/DATN/exampleSixStep/mcb_bldc_sixstep_f28069mLaunchPad_openLoop_ert_rtw" --include_path="C:/Program Files/MATLAB/R2023b/extern/include" --include_path="C:/Program Files/MATLAB/R2023b/simulink/include" --include_path="C:/Program Files/MATLAB/R2023b/rtw/c/src" --include_path="C:/Program Files/MATLAB/R2023b/rtw/c/src/ext_mode/common" --include_path="C:/Program Files/MATLAB/R2023b/rtw/c/ert" --include_path="C:/Program Files/MATLAB/R2023b/toolbox/c2b/tic2000/src" --include_path="C:/Program Files/MATLAB/R2023b/toolbox/c2b/tic2000_shared/src" --include_path="C:/Program Files/MATLAB/R2023b/toolbox/c2b/tic2000_shared/inc" --include_path="D:/TiC2000_Install/ControlSUITE/controlSUITE/device_support/f2806x/v151/F2806x_common/include" --include_path="D:/TiC2000_Install/ControlSUITE/controlSUITE/device_support/f2806x/v151/F2806x_headers/include" --include_path="D:/TiC2000_Install/ControlSUITE/controlSUITE/libs/math/CLAmath/v400/include" --include_path="D:/TiC2000_Install/ControlSUITE/controlSUITE/libs/math/IQmath/v160/include" --include_path="C:/Program Files/MATLAB/R2023b/toolbox/shared/can/src/scanutil" --include_path="D:/TiC2000_Install/ControlSUITE/controlSUITE/libs/utilities/hrcap_hccal/type0/v110/include" --include_path="C:/Program Files/MATLAB/R2023b/toolbox/c2b/tic2000_soc/src/ipclite" --include_path="C:/Program Files/MATLAB/R2023b/toolbox/c2b/tic2000_soc/inc/ipclite" --define=MW_SCHEDULER_PRIORITY=1 --define=MODEL=mcb_bldc_sixstep_f28069mLaunchPad_openLoop --define=NUMST=1 --define=NCSTATES=0 --define=HAVESTDIO --define=MODEL_HAS_DYNAMICALLY_LOADED_SFCNS=0 --define=CLASSIC_INTERFACE=0 --define=ALLOCATIONFCN=0 --define=TID01EQ=0 --define=TERMFCN=1 --define=ONESTEPFCN=1 --define=MAT_FILE=0 --define=MULTI_INSTANCE_CODE=0 --define=INTEGER_CODE=0 --define=MT=0 --define=XCP_CUSTOM_PLATFORM --define=EXTMODE_DISABLE_ARGS_PROCESSING=1 --define=MW_PIL_SCIFIFOLEN=4 --define=MW_F2806X --define=STACK_SIZE=1024 --define=__MW_TARGET_USE_HARDWARE_RESOURCES_H__ --define=RT --define=F28069M --define=CPU1 --define=BOOT_FROM_FLASH=1 --define=MW_FAST_RTS_INCLUDED=0 --define=MW_HCCAL_INCLUDED=0 --abi=coffabi -s -v28 -ml --abi=coffabi  --preproc_dependency=$(@:%.obj=%.dep) --preproc_with_compile  --large_memory_model -I$(F28_HEADERS)/include -I$(TI_INCLUDE) -v28 -ml --float_support=fpu32 -DF28069M -DCPU1 -DBOOT_FROM_FLASH=1 --preproc_with_compile --preproc_dependency="$(basename $(<F)).d_raw" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: "$<"'
	@echo ' '

mw_soc_c2000_ipc.obj: C:/Program\ Files/MATLAB/R2023b/toolbox/c2b/tic2000_soc/src/ipclite/mw_soc_c2000_ipc.c $(GEN_OPTS) | $(GEN_FILES) $(GEN_MISC_FILES)
	@echo 'Building file: "$<"'
	@echo 'Invoking: C2000 Compiler'
	"D:/TiC2000_Install/CCS/ccs/tools/compiler/ti-cgt-c2000_22.6.0.LTS/bin/cl2000" --include_path="D:/TiC2000_Install/CCS/ccs/tools/compiler/ti-cgt-c2000_22.6.0.LTS/include" --include_path="E:/GiaotrinhDH/DATN/exampleSixStep" --include_path="C:/Program Files/MATLAB/R2023b/toolbox/c2b/tic2000/inc" --include_path="E:/GiaotrinhDH/DATN/exampleSixStep/mcb_bldc_sixstep_f28069mLaunchPad_openLoop_ert_rtw" --include_path="C:/Program Files/MATLAB/R2023b/extern/include" --include_path="C:/Program Files/MATLAB/R2023b/simulink/include" --include_path="C:/Program Files/MATLAB/R2023b/rtw/c/src" --include_path="C:/Program Files/MATLAB/R2023b/rtw/c/src/ext_mode/common" --include_path="C:/Program Files/MATLAB/R2023b/rtw/c/ert" --include_path="C:/Program Files/MATLAB/R2023b/toolbox/c2b/tic2000/src" --include_path="C:/Program Files/MATLAB/R2023b/toolbox/c2b/tic2000_shared/src" --include_path="C:/Program Files/MATLAB/R2023b/toolbox/c2b/tic2000_shared/inc" --include_path="D:/TiC2000_Install/ControlSUITE/controlSUITE/device_support/f2806x/v151/F2806x_common/include" --include_path="D:/TiC2000_Install/ControlSUITE/controlSUITE/device_support/f2806x/v151/F2806x_headers/include" --include_path="D:/TiC2000_Install/ControlSUITE/controlSUITE/libs/math/CLAmath/v400/include" --include_path="D:/TiC2000_Install/ControlSUITE/controlSUITE/libs/math/IQmath/v160/include" --include_path="C:/Program Files/MATLAB/R2023b/toolbox/shared/can/src/scanutil" --include_path="D:/TiC2000_Install/ControlSUITE/controlSUITE/libs/utilities/hrcap_hccal/type0/v110/include" --include_path="C:/Program Files/MATLAB/R2023b/toolbox/c2b/tic2000_soc/src/ipclite" --include_path="C:/Program Files/MATLAB/R2023b/toolbox/c2b/tic2000_soc/inc/ipclite" --define=MW_SCHEDULER_PRIORITY=1 --define=MODEL=mcb_bldc_sixstep_f28069mLaunchPad_openLoop --define=NUMST=1 --define=NCSTATES=0 --define=HAVESTDIO --define=MODEL_HAS_DYNAMICALLY_LOADED_SFCNS=0 --define=CLASSIC_INTERFACE=0 --define=ALLOCATIONFCN=0 --define=TID01EQ=0 --define=TERMFCN=1 --define=ONESTEPFCN=1 --define=MAT_FILE=0 --define=MULTI_INSTANCE_CODE=0 --define=INTEGER_CODE=0 --define=MT=0 --define=XCP_CUSTOM_PLATFORM --define=EXTMODE_DISABLE_ARGS_PROCESSING=1 --define=MW_PIL_SCIFIFOLEN=4 --define=MW_F2806X --define=STACK_SIZE=1024 --define=__MW_TARGET_USE_HARDWARE_RESOURCES_H__ --define=RT --define=F28069M --define=CPU1 --define=BOOT_FROM_FLASH=1 --define=MW_FAST_RTS_INCLUDED=0 --define=MW_HCCAL_INCLUDED=0 --abi=coffabi -s -v28 -ml --abi=coffabi  --preproc_dependency=$(@:%.obj=%.dep) --preproc_with_compile  --large_memory_model -I$(F28_HEADERS)/include -I$(TI_INCLUDE) -v28 -ml --float_support=fpu32 -DF28069M -DCPU1 -DBOOT_FROM_FLASH=1 --preproc_with_compile --preproc_dependency="$(basename $(<F)).d_raw" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: "$<"'
	@echo ' '


